# Variables

In [1]:
%pip install numpy

Requirement already satisfied: numpy in ./.venv/lib/python3.13/site-packages (2.3.3)

[notice] A new release of pip is available: 25.2 -> 26.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np

In [1]:
name = "Alice"

In [2]:
age = 20

In [9]:
student = {
    "name": "Alice",
    "age": 20
}

In [4]:
student

{'name': 'Alice', 'age': 20}

In [5]:
student["name"]

'Alice'

In [6]:
student["age"] = 21

In [10]:
student["major"] = "IST"

In [12]:
student

{'name': 'Alice', 'age': 20, 'major': 'IST'}

In [13]:
nums = [ 1, 2, 3, 4, 5 ]

In [19]:
nums[2]

3

In [20]:
nums[0:2:1]

[1, 2]

In [22]:
for num in nums:
    print(num, end=" ")

1 2 3 4 5

In [24]:
for i in range(10):
    print(i, end=" ")

0 1 2 3 4 5 6 7 8 9

In [25]:
range(10)

range(0, 10)

In [26]:
len(nums)

5

In [32]:
nums.append(6)
nums

[1, 2, 3, 4, 5, 6, 6, 6, 6, 6, 6]

In [33]:
ans = []
for num in nums:
    ans.append(num)

In [34]:
ans

[1, 2, 3, 4, 5, 6, 6, 6, 6, 6, 6]

In [35]:
ans = []
for num in nums:
    if num % 2 == 0:
        ans.append(num)

In [36]:
ans

[2, 4, 6, 6, 6, 6, 6, 6]

In [37]:
def func():
    print("hello")

In [38]:
func()

hello

In [41]:
def add_two(num1, num2):
    return num1 + num2

total = add_two(1, 1)
total

2

## NumPy

In [4]:
import numpy as np
arr_2d = np.array([
    [5, 10, 15],
    [20, 25, 30],
    [35, 40, 45]
])

print("Element at [1, 2]:", arr_2d[0, 1])
print("Second row:", arr_2d[1])
print("First column:", arr_2d[:1])
print("Bottom-right 2x2 subarray:\n", arr_2d[1, 1:])

Element at [1, 2]: 10
Second row: [20 25 30]
First column: [[ 5 10 15]]
Bottom-right 2x2 subarray:
 [25 30]

In [12]:
import numpy as np
arr = np.arange(0, 100)
arr_2d = arr.reshape(10,10)

In [15]:
arr_2d.shape[1]

10

In [3]:
import pandas as pd
df = pd.read_csv("data/data.csv")

In [4]:
df

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  339 non-null    object
 1   Pulse     339 non-null    object
 2   Maxpulse  339 non-null    object
 3   Calories  329 non-null    object
dtypes: object(4)
memory usage: 10.7+ KB

In [6]:
df

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

In [10]:
df.head(10)

  Duration Pulse Maxpulse Calories
0       60   110      130    409.1
1       60   117      145      479
2       60   103      135      340
3       45   109      175    282.4
4       45   117      148      406
5       60   102      127    300.5
6       60   110      136      374
7       45   104      134    253.3
8       30   109      133    195.1
9       60    98      124      269

In [9]:
df.tail(3)

    Duration Pulse Maxpulse Calories
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

In [14]:
import sqlite3
conn = sqlite3.connect('./data/chinook.db')

In [15]:
query = "SELECT name FROM sqlite_master WHERE type='table';"

pd.read_sql_query(query, conn)

             name
0           Album
1          Artist
2        Customer
3        Employee
4           Genre
5         Invoice
6     InvoiceLine
7       MediaType
8        Playlist
9   PlaylistTrack
10          Track

In [16]:

df = pd.read_sql_query("SELECT * FROM customer;", conn)
df.head()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [17]:
conn.close()