# Midterm/Presentation: E-commerce Purchases - Solutions

- Note that most of these tasks can be solved in multiple ways.
- Please disregard any lack of real-world meaning in the DataFrame: the data is entirely fictional.
- Each question can be answered with a single line of code.
- Use the lecture notes and the [Pandas documentation](https://pandas.pydata.org/pandas-docs/stable/) as your main resources.
- Use AI to learn, not to cheat. Do not copy-and-paste.

Import pandas and read in the E-commerce Purchases CSV file and set it to a DataFrame called ecom.

In [1]:
import pandas as pd

In [2]:
ecom = pd.read_csv('../../data/Ecommerce Purchases')

## Q01. `df.head()` method

Check the first 5 rows (head) of the DataFrame.

In [3]:
first_5 = ecom.head()
first_5

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95
3,"7780 Julia Fords\nNew Stacy, WA 45798",36 vm,PM,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_0 ...,"Williams, Marshall and Buchanan",6011578504430710,02/24,384,Discover,brent16@olson-robinson.info,Drilling engineer,30.250.74.19,es,78.04
4,"23012 Munoz Drive Suite 337\nNew Cynthia, TX 5...",20 IE,AM,Opera/9.58.(X11; Linux x86_64; it-IT) Presto/2...,"Brown, Watson and Andrews",6011456623207998,10/25,678,Diners Club / Carte Blanche,christopherwright@gmail.com,Fine artist,24.140.33.94,es,77.82

Show the first 3 rows of the DataFrame

In [4]:
first_3 = ecom.head(3)
first_3

,Address,Lot,AM or PM,Browser Info,Company,Credit Card,CC Exp Date,CC Security Code,CC Provider,Email,Job,IP Address,Language,Purchase Price
0,"16629 Pace Camp Apt. 448\nAlexisborough, NE 77...",46 in,PM,Opera/9.56.(X11; Linux x86_64; sl-SI) Presto/2...,Martinez-Herman,6011929061123406,02/20,900,JCB 16 digit,pdunlap@yahoo.com,"Scientist, product/process development",149.146.147.205,el,98.14
1,"9374 Jasmine Spurs Suite 508\nSouth John, TN 8...",28 rn,PM,Opera/8.93.(Windows 98; Win 9x 4.90; en-US) Pr...,"Fletcher, Richards and Whitaker",3337758169645356,11/18,561,Mastercard,anthony41@reed.com,Drilling engineer,15.160.41.51,fr,70.73
2,Unit 0065 Box 5052\nDPO AP 27450,94 vE,PM,Mozilla/5.0 (compatible; MSIE 9.0; Windows NT ...,"Simpson, Williams and Pham",675957666125,08/19,699,JCB 16 digit,amymiller@morales-harrison.com,Customer service manager,132.207.160.22,de,0.95

## Q02. [`df.info()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.info.html#pandas.DataFrame.info) method
How many rows and columns are there (use the info method)

In [5]:
info = ecom.info()
print(info)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Address           10000 non-null  object
 1   Lot               10000 non-null  object
 2   AM or PM          10000 non-null  object
 3   Browser Info      10000 non-null  object
 4   Company           10000 non-null  object
 5   Credit Card       10000 non-null  int64
 6   CC Exp Date       10000 non-null  object
 7   CC Security Code  10000 non-null  int64
 8   CC Provider       10000 non-null  object
 9   Email             10000 non-null  object
 10  Job               10000 non-null  object
 11  IP Address        10000 non-null  object
 12  Language          10000 non-null  object
 13  Purchase Price    10000 non-null  float64
dtypes: float64(1), int64(2), object(11)
memory usage: 1.1+ MB
None

## Q03. dtype & dtypes

- Check the data types of the DataFrame and the column 'Credit Card'.
- Use f-string to print with '\n' to produce the same result.

In [6]:
df_dtypes = ecom.dtypes
cc_dtype = ecom['Credit Card'].dtype

print(f"The dtypes of ecom:\n{df_dtypes}\n")
print(f"The dtype of 'Credit Card' is:\n{cc_dtype}")

The dtypes of ecom:
Address              object
Lot                  object
AM or PM             object
Browser Info         object
Company              object
Credit Card           int64
CC Exp Date          object
CC Security Code      int64
CC Provider          object
Email                object
Job                  object
IP Address           object
Language             object
Purchase Price      float64
dtype: object

The dtype of 'Credit Card' is:
int64

## Q04. Shape & Indexing

- Check the number of rows and columns in one line of code each (use the shape attribute). 
- Use f-string to print.

In [7]:
n_rows = ecom.shape[0]
n_cols = ecom.shape[1]
print(f"The number of rows is {n_rows}")
print(f"The number of colums is {n_cols}")

The number of rows is 10000
The number of colums is 14

## Q05. Indexing and Aggregations
What are the highest, lowest, and average Purchase prices?

In [8]:
h_pp = ecom['Purchase Price'].max()
l_pp = ecom['Purchase Price'].min()
avg_pp = ecom['Purchase Price'].mean()

print(f"The highest in 'Purchase Price': {h_pp}")
print(f"The lowest in 'Purchase Price:' {l_pp}")
print(f"The average in 'Purchase Price': {avg_pp}")

The highest in 'Purchase Price': 99.99
The lowest in 'Purchase Price:' 0.0
The average in 'Purchase Price': 50.347302

## Q06. Conditional Selection & Counting

How many people have English 'en' as their Language of choice on the website?

In [9]:
en_count = ecom[ecom['Language']=='en']['Language'].count()      ### works
# en_count = len(ecom[ecom['Language']=='en'])                     ### also works
print(en_count)

1098

## Q07. Conditional Selection and Count

How many people have the job title of "Lawyer"? (use the [`count()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.count.html#pandas.DataFrame.count) method)

In [10]:
n_lawyer = ecom[ ecom['Job'] == 'Lawyer' ]['Job'].count()
print(n_lawyer)

30

## Q08. `value_counts()` & Series Indexing

How many people made the purchase during the AM, and how many people made the purchase during the PM? (check out the [`value_counts()`](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.value_counts.html) method. `value_counts()` does frequency distribution aggregation)

In [11]:
am_pm = ecom['AM or PM'].value_counts()
am = am_pm.iloc[0]
pm = am_pm.iloc[1]
print(f"AM: {am}")
print(f"PM: {pm}")

AM: 5068
PM: 4932

## Q09 `value_counts()`, ser.index, & For Loop

What are the 5 most common Job Titles? Print out the Series and the titles.

In [12]:
top_5 = ecom['Job'].value_counts().head()

print(top_5)
print()
for job in top_5.index:
    print(job)

Job
Interior and spatial designer    31
Lawyer                           30
Social researcher                28
Purchasing manager               27
Designer, jewellery              27
Name: count, dtype: int64

Interior and spatial designer
Lawyer
Social researcher
Purchasing manager
Designer, jewellery

## Q10. Conditional Selection

Someone made a purchase that came from Lot: "90 WT". What was the Purchase Price for this transaction?

In [13]:
price = ecom[ ecom['Lot'] == '90 WT']['Purchase Price']
print(f"{price} \n")
print(f"Just price: {price.iloc[0]}")

513    75.1
Name: Purchase Price, dtype: float64

Just price: 75.1

## Q11 Conditional Selection

What is the email of the person with the following Credit Card Number: 4926535242672853?

In [14]:
email = ecom[ ecom['Credit Card'] == 4926535242672853 ]['Email']
print(f"{email}\n")
print(f"{email.iloc[0]}")

1234    bondellen@williams-garza.com
Name: Email, dtype: object

bondellen@williams-garza.com

## Q12. Boolean Indexing

How many people have American Express as their Credit Card Provider *and* made a purchase above $95 ?**

In [15]:
amex_95 = ecom[ (ecom['CC Provider'] == 'American Express') & (ecom['Purchase Price'] > 95) ].count()
print(f"{amex_95}\n")
print(f"{amex_95.iloc[0]}")

Address             39
Lot                 39
AM or PM            39
Browser Info        39
Company             39
Credit Card         39
CC Exp Date         39
CC Security Code    39
CC Provider         39
Email               39
Job                 39
IP Address          39
Language            39
Purchase Price      39
dtype: int64

39

## Q13. 

How many people have a credit card that expires in 2025? **

In [16]:
sum(ecom['CC Exp Date'].apply(lambda x: x[3:]) == '25')

1033

## Q14. 

What are the top 5 most popular email providers/hosts (e.g. gmail.com, yahoo.com, etc...) **

In [17]:
ecom['Email'].apply(lambda x: x.split('@')[1]).value_counts().head(5)

Email
hotmail.com     1638
yahoo.com       1616
gmail.com       1605
smith.com         42
williams.com      37
Name: count, dtype: int64