# Seaborn

Seaborn is a higher-level library built on top of Matplotlib. It's specifically designed for creating more visually appealing and informative statistical graphics with less code. It's excellent for exploring relationships between variables. 

Seaborn also requires Matplotlib as a dependency.

In [2]:
import seaborn as sns 
import pandas as pd 
import matplotlib.pyplot as plt

## Loading Sample Datasets 

Seaborn comes with several built-in datasets that are useful for practice and examples.

In [5]:
# load the Iris dataset 
iris = sns.load_dataset('iris') 
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [7]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa