# Pandas DataFrames

DataFrames are the core data structure in Pandas, modeled after similar structures in the **R** programming language. A DataFrame is a **two-dimensional, labeled data structure** that can be thought of as:

- A **collection of Series objects** combined into a single table, all sharing the same index
- A **spreadsheet or SQL table** with rows and columns
- A **dictionary of Series**, where each column is a Series with a shared index

**Key Features of DataFrames**

- **Labeled axes**: Both rows (index) and columns have labels, making data access intuitive and explicit
- **Heterogeneous data**: Different columns can contain different data types (integers, floats, strings, dates, etc.)
- **Size-mutable**: You can insert and delete columns
- **Powerful operations**: Built-in methods for filtering, grouping, merging, reshaping, and statistical analysis
- **Alignment** of data based on labels
- **Missing data** handling (see [0404-missing-data.ipynb](0404-missing-data.ipynb) for details)
- **Rich I/O tools** for reading/writing various formats (CSV, Excel, SQL, JSON, etc.)

**Why DataFrames?**

While NumPy arrays are excellent for numerical computation, DataFrames offer several advantages:

- **Column names** instead of just numeric indices
- **Mixed data types** in different columns
- Accessing and selecting data
- Modifying DataFrames (adding/removing columns and rows)
- Sorting and filtering
- Working with indices, including MultiIndex

**What You'll Learn**

In this notebook, we'll explore:

1. Creating DataFrames from various sources
2. DataFrame attributes and methods
3. Indexing and selecting data
4. Sorting and filtering
5. Working with indices, including MultiIndex
6. Performance tips and best practices

**Note:** Missing data handling is covered in detail in notebook [0404-missing-data.ipynb](0404-missing-data.ipynb).

Let's use Pandas to explore how DataFrames work!

**Additional Resources:**
- [Official Pandas Documentation](https://pandas.pydata.org/docs/)
- [DataFrame API Reference](https://pandas.pydata.org/docs/reference/frame.html)
- [10 Minutes to Pandas](https://pandas.pydata.org/docs/user_guide/10min.html)

In [105]:
# %pip install pandas       # Uncomment to install if you haven't already
import numpy as np
import pandas as pd

## Reading Datasets

Following the instruction in [Handling Dataset](https://thinkdsm.org/chapters/04-pandas/02-pd-handle-datasets.html), you are able to access the dataset files in your data directory.

### read_csv( ) to read file

- The most common way to read a file is to use `read_csv`.
- We'll use `data.csv`, a simple dataset for demonstration purposes.
- [read_csv documentation](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) for all available parameters

In [106]:
# Read CSV file - both forward slashes (/) work on Windows, macOS, and Linux

df = pd.read_csv("../../data/data.csv")
df

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

Now that we have the DataFrame object, let's use `df.info()` to get the:
1. data type
2. number of values in the column
3. Null values

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  339 non-null    object
 1   Pulse     339 non-null    object
 2   Maxpulse  339 non-null    object
 3   Calories  329 non-null    object
dtypes: object(4)
memory usage: 10.7+ KB

### df Output

There are several ways to display a DataFrame, each with different formatting and truncation behavior:

| Method | Description |
|--------|-------------|
| `df` | Displays DataFrame in table format with first/last 5 rows by default |
| `print(df)` | Prints text representation showing header(5) and tail(5) rows |
| `to_string()` | Converts entire DataFrame to string without truncation |
| `pd.options.display.max_rows` | Controls how many rows are displayed before truncation |

In [109]:
df      # Default view is table-like
        # Pandas will show first 5 and last 5 rows (10 total) by default
        # The shape information is displayed at the bottom

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

In [127]:
print(df)   # print() shows same information but in plain text format

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

Sometimes, you need to see more than the default output. You use the pd.options.display.max_rows attribute.

In [128]:
print(pd.options.display.max_rows, "\n")    # Display max_rows is typically 60 by default (system-dependent)
print(df.head(), "\n")                      # head() shows the first n rows, default n=5
print(df.tail(3), "\n")                     # tail() shows the last n rows, default n=5
print(df.head(7))                           # If n exceeds max_rows, output will be truncated

50

  Duration Pulse Maxpulse Calories
0       60   110      130    409.1
1       60   117      145      479
2       60   103      135      340
3       45   109      175    282.4
4       45   117      148      406

    Duration Pulse Maxpulse Calories
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

  Duration Pulse Maxpulse Calories
0       60   110      130    409.1
1       60   117      145      479
2       60   103      135      340
3       45   109      175    282.4
4       45   117      148      406
5       60   102      127    300.5
6       60   110      136      374

In [129]:
pd.options.display.max_rows = 50     # Set max_rows display limit

In [130]:
# This line is commented out to avoid overwhelming output
# Uncomment it to see the full DataFrame without truncation

# print(df.to_string())          # to_string() prints the entire DataFrame

In [ ]:
### EXERCISE: Reading CSV Files
#
# Using the data/baby.csv file:
# 1. Read the CSV file into a DataFrame called baby_df
# 2. Display the first 7 rows
# 3. Display the last 3 rows
# 4. Check the shape of the DataFrame
# 5. Get the column names
#
### Your code starts here:





### Your code ends here.

In [ ]:
# Solution

# 1. Read the CSV file
baby_df = pd.read_csv('../../data/baby.csv')

# 2. Display first 7 rows
print("First 7 rows:")
print(baby_df.head(7))
print()

# 3. Display last 3 rows
print("Last 3 rows:")
print(baby_df.tail(3))
print()

# 4. Check the shape
print("Shape:", baby_df.shape)
print()

# 5. Get column names
print("Columns:", baby_df.columns.tolist())

## DataFrame Attributes & Methods

DataFrames have many useful attributes and methods that help us understand the structure and content of our data. Let's explore the most commonly used ones.

### Shape and Size

In [131]:
# Get the dimensions of the DataFrame (rows, columns)
df.shape

(339, 4)

In [132]:
# Get the total number of elements (rows * columns)
df.size

1356

In [133]:
# Get the number of rows
len(df)

339

### Columns and Index

In [134]:
# Get all column names
df.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [135]:
# Get the index (row labels)
df.index

RangeIndex(start=0, stop=339, step=1)

### Data Types

In [136]:
# Get the data type of each column
df.dtypes

Duration    object
Pulse       object
Maxpulse    object
Calories    object
dtype: object

### Statistical Summary

The `describe()` method provides different statistics depending on column data types:

- **Numeric columns**: count, mean, std, min, quartiles, max
- **Object/categorical columns**: count, unique, top (most common value), freq (frequency of top value)

In [ ]:
# Get statistical summary of numeric columns
df.describe()

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10

### Previewing Data

When working with large datasets, you often want to see just a sample of the data rather than the entire DataFrame.

In [140]:
# View first 5 rows (default)
df.head()

  Duration Pulse Maxpulse Calories
0       60   110      130    409.1
1       60   117      145      479
2       60   103      135      340
3       45   109      175    282.4
4       45   117      148      406

In [141]:
# View last 3 rows
df.tail(3)

    Duration Pulse Maxpulse Calories
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

### Reading from SQLite Databases

Beyond CSV files, Pandas can read from many data sources. Let's explore loading data from a SQLite database that we've used in previous SQL activities. You'll appreciate how convenient Pandas makes this!

To connect to a SQLite database, we:
1. Import the sqlite3 library (part of Python's standard library)
2. Connect to the database using `sqlite3.connect()`
3. Use the Pandas function `read_sql_query()` to execute your query
4. Close the connection using the `close()` function (or use `with` statement)

In [ ]:
### List all tables in the SQLite database (similar to "SHOW TABLES;" in MySQL)

import sqlite3
conn = sqlite3.connect('../../data/chinook.db')

query = "SELECT name FROM sqlite_master WHERE type='table';"

pd.read_sql_query(query, conn)

             name
0           Album
1          Artist
2        Customer
3        Employee
4           Genre
5         Invoice
6     InvoiceLine
7       MediaType
8        Playlist
9   PlaylistTrack
10          Track

In [145]:
import sqlite3
conn = sqlite3.connect('../../data/chinook.db')

df = pd.read_sql_query("SELECT * FROM customer;", conn)
df.head()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [146]:
# Always close database connections when done

conn.close()

In [ ]:
# BETTER PRACTICE: Use 'with' statement to automatically close connection
# The 'with' statement ensures the connection is closed even if an error occurs

sql = 'SELECT * FROM Artist LIMIT 10'
with sqlite3.connect("../../data/chinook.db") as conn:
    df = pd.read_sql_query(sql, conn)

df

   ArtistId                  Name
0         1                 AC/DC
1         2                Accept
2         3             Aerosmith
3         4     Alanis Morissette
4         5       Alice In Chains
5         6  Antônio Carlos Jobim
6         7          Apocalyptica
7         8            Audioslave
8         9              BackBeat
9        10          Billy Cobham

In [ ]:
### EXERCISE: DataFrame Inspection
#
# Using the df DataFrame from the previous cells:
# 1. Get the number of rows and columns
# 2. Get the data types of each column
# 3. Get statistical summary of the DataFrame
# 4. Get the index values
# 5. Count the total number of elements
#
### Your code starts here:





### Your code ends here.

In [ ]:
# Solution

# 1. Number of rows and columns
print("Shape (rows, columns):", df.shape)
print()

# 2. Data types
print("Data types:")
print(df.dtypes)
print()

# 3. Statistical summary
print("Statistical summary:")
print(df.describe())
print()

# 4. Index values
print("Index:", df.index.tolist())
print()

# 5. Total elements
print("Total elements:", df.size)

## Creating DataFrames

Now that you've seen how to read DataFrames from files and databases, let's learn how to create them from scratch. This is useful for testing, small datasets, or when you need to build data programmatically.

### Using pd.DataFrame()

The `pd.DataFrame()` constructor creates a DataFrame object from various input types including dictionaries, lists, NumPy arrays, and more.

In [153]:
# Create a date index using pd.date_range()
# This function generates a range of dates similar to how range() generates numbers

# dates = pd.date_range()     # Shift+Tab to see documentation
dates = pd.date_range("20250901", periods=6)

In [154]:
# Evaluate the dates variable; dtype is datetime64 and freq='D' (daily frequency)

dates

DatetimeIndex(['2025-09-01', '2025-09-02', '2025-09-03', '2025-09-04',
               '2025-09-05', '2025-09-06'],
              dtype='datetime64[ns]', freq='D')

In [155]:
# Check the data type: it's a DatetimeIndex object

type(dates)

pandas.core.indexes.datetimes.DatetimeIndex

In [156]:
# Convert a string to a list of characters for column labels

list("ABCD")

['A', 'B', 'C', 'D']

In [ ]:
# Create a DataFrame using pd.DataFrame()
# pd.DataFrame    # Shift+Tab to see documentation

# Set random seed for reproducibility (ensures same "random" numbers each time)
np.random.seed(42)

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

In [158]:
df

                   A         B         C         D
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304
2025-09-06  1.465649 -0.225776  0.067528 -1.424748

In [159]:
# Verify the type: this confirms we have a DataFrame object

type(df)

pandas.core.frame.DataFrame

In [ ]:
### EXERCISE: Creating DataFrames from Scratch
#
# Create a DataFrame with the following specifications:
# - Columns: 'Name', 'Age', 'City', 'Score'
# - Data for at least 4 people with their information
# - Use a custom index (e.g., 'S1', 'S2', 'S3', 'S4')
#
# Then:
# 1. Display the DataFrame
# 2. Select the 'Name' and 'Score' columns (should return a DataFrame with 2 columns)
# 3. Add a new column 'Pass' that is True if Score >= 70, False otherwise
#
# Tip: Use pd.DataFrame() with a dictionary where keys are column names
#
### Your code starts here:





### Your code ends here.

In [ ]:
# Solution

# Create the DataFrame
students_df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [20, 22, 21, 23],
    'City': ['NYC', 'LA', 'Chicago', 'Boston'],
    'Score': [85, 92, 67, 78]
}, index=['S1', 'S2', 'S3', 'S4'])

# 1. Display the DataFrame
print("Students DataFrame:")
print(students_df)
print()

# 2. Select Name and Score columns
print("Name and Score:")
print(students_df[['Name', 'Score']])
print()

# 3. Add Pass column
students_df['Pass'] = students_df['Score'] >= 70
print("With Pass column:")
print(students_df)

## DataFrame Indexing

In this section, we examine the primary techniques for retrieving data stored within a Pandas DataFrame. Mastery of these methods is essential, as they allow us to isolate rows, columns, or specific values for further analysis.

**See also:** [Indexing and Selecting Data (Official Guide)](https://pandas.pydata.org/docs/user_guide/indexing.html)

Let's create a sample DataFrame with employee salary data for demonstration:

In [72]:
### Create DataFrame with employee salary data (in thousands)
### This is more meaningful than random numbers

df = pd.DataFrame({
    'Salary': [75, 82, 68, 91, 55],
    'Bonus': [8.5, 12.3, 5.2, 15.8, 3.1],
    'Years': [3, 5, 2, 7, 1],
    'Rating': [4.2, 4.7, 3.8, 4.9, 3.5]
}, index=['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'])

df

         Salary  Bonus  Years  Rating
Alice        75    8.5      3     4.2
Bob          82   12.3      5     4.7
Charlie      68    5.2      2     3.8
Diana        91   15.8      7     4.9
Eve          55    3.1      1     3.5

### 1. Column Selection

#### Single Column
Select a single column using bracket notation. The result is a Series.

In [73]:
### Use bracket notation to select a single column

df['Salary']

Alice      75
Bob        82
Charlie    68
Diana      91
Eve        55
Name: Salary, dtype: int64

In [ ]:
### WARNING: This works but is NOT RECOMMENDED
### Can conflict with DataFrame methods or fail with column names containing spaces/special characters

df.Salary

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

#### Multiple Columns
Pass a list of column names to select multiple columns. The result is a DataFrame.

In [ ]:
### Pass a list of column names

df[['Salary','Rating']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

DataFrame Columns are just Series

In [ ]:
type(df['Salary'])

pandas.core.series.Series

### 2. Row Selection

Accessing DataFrame rows with **loc** (label-based) and **iloc** (position-based).

#### Using .loc[ ] - Label-based indexing

In [ ]:
df.loc['Alice']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [ ]:
ser = df.loc['Alice']
type(ser)

pandas.core.series.Series

#### Using .iloc[ ] - Position-based indexing
Select based on integer position instead of label:

In [ ]:
### Get the third row (index position 2) - Charlie's data
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

### 3. Selecting Rows and Columns Together

Use `.loc[]` or `.iloc[]` to select specific rows and columns simultaneously.

In [37]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
### Get Alice's Salary (single value)
df.loc['Alice', 'Salary']

np.float64(-0.8480769834036315)

In [ ]:
### Get Salary and Rating for Alice and Bob
df.loc[['Alice','Bob'],['Salary','Rating']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

### Fast Scalar Access with .at[] and .iat[]

For accessing **single values** (scalars), `.at[]` and `.iat[]` are faster alternatives to `.loc[]` and `.iloc[]`.

- **`.at[]`** - label-based, for single value access
- **`.iat[]`** - position-based, for single value access

Use these when you only need one value, as they're optimized for speed.

In [ ]:
# Using .at[] for fast label-based access to a single value
df.at['Alice', 'Salary']

In [ ]:
# Using .iat[] for fast position-based access
# Get value at row 0, column 0 (Alice's Salary)
df.iat[0, 0]

In [ ]:
# Performance comparison: .at[] is faster than .loc[] for single values
# .loc[] works, but .at[] is optimized for this use case
print("Using .loc[]:", df.loc['Bob', 'Rating'])
print("Using .at[]:", df.at['Bob', 'Rating'])

### 4. Conditional Selection (Boolean Indexing)

An important feature of pandas is conditional selection using bracket notation, very similar to numpy. This allows us to filter rows based on conditions.

In [40]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [41]:
df>0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [42]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
### Get all employees with Salary > 70
df[df['Salary']>70]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
### Get Years for employees with Salary > 70
df[df['Salary']>70]['Years']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [ ]:
### WARNING: Chained indexing like this can be problematic
### Better to use .loc[] as shown below

df[df['Salary']>70][['Years','Bonus']]

In [ ]:
### BETTER PRACTICE: Use .loc[] for row and column selection together
df.loc[df['Salary']>70, ['Years','Bonus']]

#### Multiple Conditions

**Common Pitfall**: Use `&` and `|`, NOT `and` or `or`. Python's `and`/`or` don't work with pandas boolean indexing.

For two or more conditions, use `|` (OR) and `&` (AND) with parentheses.

In [ ]:
### Combine conditions with & (and) or | (or)
### Each condition must be in parentheses

df[(df['Salary']>70) & (df['Years'] > 2)]

#### Alternative: Using .query() Method

The `.query()` method offers a more readable way to filter DataFrames, especially with multiple conditions.

In [ ]:
# Same result as above, but more readable
df.query('Salary > 70 and Years > 2')

In [ ]:
# .query() also supports variables using @ symbol
min_salary = 70
df.query('Salary > @min_salary')

### Row/Column Operations

#### Creating a new column:

Note that this is in-place.

In [ ]:
### Create a new column: Total Compensation
df['TotalComp'] = df['Salary'] + df['Bonus']

In [48]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

#### Dropping columns

Using the drop function. Note that you have to specify **axis=1** to drop the column label.

**Understanding axis parameter:**
- `axis=0` → operates on **rows** (index) - "go down the rows"
- `axis=1` → operates on **columns** - "go across the columns"

**Mnemonic**: Think of axis as the direction you're moving. axis=0 goes down (rows), axis=1 goes across (columns).

In [ ]:
df.drop('TotalComp',axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [165]:
# Not modified! Most DataFrame operations are not in-place by default
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

**Important**: Most DataFrame operations return a **new** DataFrame (a "**view**") and do NOT modify the original unless you specify **inplace=True**.

In [ ]:
df.drop('TotalComp',axis=1,inplace=True)

df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [ ]:
### Now 'TotalComp' column is permanently removed
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

#### Dropping rows

Note that **axis=0**.

In [ ]:
### Drop Eve's row (axis=0 for rows)
df.drop('Eve', axis=0)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [ ]:
### EXERCISE: DataFrame Indexing Practice
#
# Given the following sales data:
sales_data = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam'],
    'Q1': [50, 200, 150, 75, 90],
    'Q2': [65, 210, 160, 80, 95],
    'Q3': [70, 190, 155, 85, 100],
    'Q4': [80, 220, 170, 90, 110]
}, index=['P1', 'P2', 'P3', 'P4', 'P5'])
#
# Tasks:
# 1. Select the Q2 and Q4 columns
# 2. Select rows P2 and P4
# 3. Select Q3 sales for rows P1, P3, and P5 (should return a Series)
# 4. Add a new column 'Total' that sums Q1 through Q4 (Tip: use .sum(axis=1))
# 5. Drop the Q1 column (without modifying the original DataFrame)
#
# Hint: Use double brackets [[]] for selecting multiple columns
#
### Your code starts here:





### Your code ends here.

In [ ]:
# Solution

sales_data = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam'],
    'Q1': [50, 200, 150, 75, 90],
    'Q2': [65, 210, 160, 80, 95],
    'Q3': [70, 190, 155, 85, 100],
    'Q4': [80, 220, 170, 90, 110]
}, index=['P1', 'P2', 'P3', 'P4', 'P5'])

# 1. Select Q2 and Q4 columns
print("Q2 and Q4 columns:")
print(sales_data[['Q2', 'Q4']])
print()

# 2. Select rows P2 and P4
print("Rows P2 and P4:")
print(sales_data.loc[['P2', 'P4']])
print()

# 3. Select Q3 sales for P1, P3, P5
print("Q3 for P1, P3, P5:")
print(sales_data.loc[['P1', 'P3', 'P5'], 'Q3'])
print()

# 4. Add Total column
sales_data['Total'] = sales_data[['Q1', 'Q2', 'Q3', 'Q4']].sum(axis=1)
print("With Total column:")
print(sales_data)
print()

# 5. Drop Q1 column (returns new DataFrame)
print("After dropping Q1:")
print(sales_data.drop('Q1', axis=1))

## DataFrame Operations

This section covers common DataFrame manipulation operations including sorting, handling duplicates, and renaming.

### Sorting DataFrames

Let's return to our main DataFrame and explore sorting operations. Sorting is essential for data analysis. Pandas provides methods to sort by values or by index.

In [19]:
### Recreate DataFrame with random data for sorting examples
np.random.seed(42)
dates = pd.date_range('20250901', periods=5)
df = pd.DataFrame(np.random.randn(5, 4), index=dates, columns=list('WXYZ'))
df

                   W         X         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

#### Sorting by Values

In [20]:
# Sort by a single column (ascending)
df.sort_values(by='W')

                   W         X         Y         Z
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-01  0.496714 -0.138264  0.647689  1.523030

In [21]:
# Sort by a column in descending order
df.sort_values(by='W', ascending=False)

                   W         X         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

In [22]:
# Sort by multiple columns
df.sort_values(by=['W', 'Z'])

                   W         X         Y         Z
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-01  0.496714 -0.138264  0.647689  1.523030

#### Sorting by Index

In [23]:
# Sort by index labels
df.sort_index()

                   W         X         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

In [24]:
# Sort index in descending order
df.sort_index(ascending=False)

                   W         X         Y         Z
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-01  0.496714 -0.138264  0.647689  1.523030

In [25]:
### EXERCISE: Sorting DataFrames
#
# Create a DataFrame:
sort_df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 22, 28],
    'Score': [85, 92, 78, 92]
})
#
# Tasks:
# 1. Sort by Age in ascending order
# 2. Sort by Score in descending order
# 3. Sort by Score (descending), then by Age (ascending)
# 4. Sort by index
#
### Your code starts here:





### Your code ends here.

In [26]:
# Solution

sort_df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 22, 28],
    'Score': [85, 92, 78, 92]
})

# 1. Sort by Age (ascending)
print("Sorted by Age:")
print(sort_df.sort_values(by='Age'))
print()

# 2. Sort by Score (descending)
print("Sorted by Score (descending):")
print(sort_df.sort_values(by='Score', ascending=False))
print()

# 3. Sort by Score (desc), then Age (asc)
print("Sorted by Score (desc) then Age:")
print(sort_df.sort_values(by=['Score', 'Age'], ascending=[False, True]))
print()

# 4. Sort by index
print("Sorted by index:")
print(sort_df.sort_index())

Sorted by Age:
      Name  Age  Score
2  Charlie   22     78
0    Alice   25     85
3    Diana   28     92
1      Bob   30     92

Sorted by Score (descending):
      Name  Age  Score
1      Bob   30     92
3    Diana   28     92
0    Alice   25     85
2  Charlie   22     78

Sorted by Score (desc) then Age:
      Name  Age  Score
3    Diana   28     92
1      Bob   30     92
0    Alice   25     85
2  Charlie   22     78

Sorted by index:
      Name  Age  Score
0    Alice   25     85
1      Bob   30     92
2  Charlie   22     78
3    Diana   28     92

### Handling Duplicates

DataFrames often contain duplicate rows. Pandas provides methods to identify and remove them.

In [27]:
# Create a DataFrame with duplicates for demonstration
df_dup = pd.DataFrame({
    'A': [1, 2, 2, 3, 4],
    'B': [5, 6, 6, 7, 8]
})
df_dup

   A  B
0  1  5
1  2  6
2  2  6
3  3  7
4  4  8

In [28]:
# Check for duplicate rows (returns boolean Series)
df_dup.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [29]:
# Drop duplicate rows (keeps first occurrence by default)
df_dup.drop_duplicates()

   A  B
0  1  5
1  2  6
3  3  7
4  4  8

In [30]:
# Drop duplicates based on specific columns
df_dup.drop_duplicates(subset=['A'])

   A  B
0  1  5
1  2  6
3  3  7
4  4  8

In [31]:
### EXERCISE: Identifying and Removing Duplicates
#
# Create a DataFrame with duplicate rows:
dup_df = pd.DataFrame({
    'A': [1, 2, 2, 3, 3, 4],
    'B': [10, 20, 20, 30, 30, 40],
    'C': ['x', 'y', 'y', 'z', 'w', 'v']
})
#
# Tasks:
# 1. Display the DataFrame
# 2. Check which rows are duplicates
# 3. Remove all duplicate rows
# 4. Remove duplicates based only on column 'A'
#
### Your code starts here:





### Your code ends here.

In [32]:
# Solution

dup_df = pd.DataFrame({
    'A': [1, 2, 2, 3, 3, 4],
    'B': [10, 20, 20, 30, 30, 40],
    'C': ['x', 'y', 'y', 'z', 'w', 'v']
})

# 1. Display the DataFrame
print("Original DataFrame:")
print(dup_df)
print()

# 2. Check for duplicates
print("Duplicate rows:")
print(dup_df.duplicated())
print()

# 3. Remove all duplicates
print("After removing all duplicates:")
print(dup_df.drop_duplicates())
print()

# 4. Remove duplicates based on column A
print("After removing duplicates in column A:")
print(dup_df.drop_duplicates(subset=['A']))

Original DataFrame:
   A   B  C
0  1  10  x
1  2  20  y
2  2  20  y
3  3  30  z
4  3  30  w
5  4  40  v

Duplicate rows:
0    False
1    False
2     True
3    False
4    False
5    False
dtype: bool

After removing all duplicates:
   A   B  C
0  1  10  x
1  2  20  y
3  3  30  z
4  3  30  w
5  4  40  v

After removing duplicates in column A:
   A   B  C
0  1  10  x
1  2  20  y
3  3  30  z
5  4  40  v

### Renaming Columns and Index

Renaming makes your data more readable and easier to work with.

In [33]:
df

                   W         X         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

In [34]:
# Rename columns using a dictionary
df.rename(columns={'W': 'Weight', 'X': 'X-axis'})

              Weight    X-axis         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

In [35]:
# Rename index
df.rename(index={'A': 'Alpha', 'B': 'Beta'})

                   W         X         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

In [36]:
# Use inplace=True to modify the DataFrame
df_renamed = df.rename(columns={'W': 'Weight', 'X': 'X-axis'}, inplace=False)
df_renamed

              Weight    X-axis         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

In [37]:
### EXERCISE: Renaming DataFrame Elements
#
# Create a DataFrame:
rename_df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8, 9]
}, index=['row1', 'row2', 'row3'])
#
# Tasks:
# 1. Display the original DataFrame
# 2. Rename column 'a' to 'Alpha' and 'b' to 'Beta'
# 3. Rename the index 'row1' to 'R1' and 'row2' to 'R2'
# 4. Display the renamed DataFrame
#
### Your code starts here:





### Your code ends here.

In [38]:
# Solution

rename_df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8, 9]
}, index=['row1', 'row2', 'row3'])

# 1. Display original
print("Original DataFrame:")
print(rename_df)
print()

# 2. Rename columns
rename_df = rename_df.rename(columns={'a': 'Alpha', 'b': 'Beta'})

# 3. Rename index
rename_df = rename_df.rename(index={'row1': 'R1', 'row2': 'R2'})

# 4. Display renamed DataFrame
print("After renaming:")
print(rename_df)

Original DataFrame:
      a  b  c
row1  1  4  7
row2  2  5  8
row3  3  6  9

After renaming:
      Alpha  Beta  c
R1        1     4  7
R2        2     5  8
row3      3     6  9

## Applying Functions with `.apply()`

The `.apply()` method is a powerful tool that allows you to apply a function along an axis of the DataFrame (rows or columns). This is useful for transformations, calculations, and custom operations.

The syntax for `.apply()` is:

```python
DataFrame.apply(func, axis=0, raw=False, result_type=None, args=(), **kwargs)
```

**Parameters:**
- `func`: Function to apply to each column or row
- `axis`: {0 or 'index', 1 or 'columns'}, default 0
  - 0 or 'index': apply function to each column
  - 1 or 'columns': apply function to each row
- `raw`: bool, default False. If False, passes each row/column as a Series to the function. If True, passes ndarray
- `result_type`: {'expand', 'reduce', 'broadcast', None}, default None
- `args`: tuple, positional arguments to pass to func
- `**kwargs`: additional keyword arguments to pass to func

**Returns:** Series or DataFrame

**Performance Note:** For simple operations like arithmetic or comparisons, vectorized operations are usually faster than `.apply()`. Use `.apply()` when you need to apply a complex function that can't be vectorized.

```python
# Vectorized (faster): df['A'] * 2
# Using apply (slower): df['A'].apply(lambda x: x * 2)
```

In [39]:
df

                   W         X         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

In [40]:
# Apply a function to each column (axis=0, default)
print(df.apply(np.sum))
print(type(df.apply(np.sum)))

W   -0.977782
X   -1.428874
Y   -0.869458
Z   -0.149856
dtype: float64
<class 'pandas.core.series.Series'>

In [41]:
# Apply a function to each row (axis=1)
df.apply(np.sum, axis=1)

2025-09-01    2.529168
2025-09-02    1.878357
2025-09-03   -0.856062
2025-09-04   -3.958523
2025-09-05   -3.018912
Freq: D, dtype: float64

In [42]:
# Apply a custom function (double each value)
df.apply(lambda x: x * 2)

                   W         X         Y         Z
2025-09-01  0.993428 -0.276529  1.295377  3.046060
2025-09-02 -0.468307 -0.468274  3.158426  1.534869
2025-09-03 -0.938949  1.085120 -0.926835 -0.931460
2025-09-04  0.483925 -3.826560 -3.449836 -1.124575
2025-09-05 -2.025662  0.628495 -1.816048 -2.824607

In [43]:
# Apply to a single column
df['W'].apply(lambda x: x ** 2)

2025-09-01    0.246725
2025-09-02    0.054828
2025-09-03    0.220406
2025-09-04    0.058546
2025-09-05    1.025827
Freq: D, Name: W, dtype: float64

In [44]:
### EXERCISE: Applying Functions
#
# Create a DataFrame:
apply_df = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': [10, 20, 30, 40],
    'C': [100, 200, 300, 400]
})
#
# Tasks:
# 1. Apply a function to get the sum of each column
# 2. Apply a function to get the maximum value in each row
# 3. Apply a lambda function to double all values in column A
# 4. Apply a custom function that adds 5 to all values
#
### Your code starts here:





### Your code ends here.

In [45]:
# Solution

apply_df = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': [10, 20, 30, 40],
    'C': [100, 200, 300, 400]
})

# 1. Sum of each column
print("Sum of each column:")
print(apply_df.apply(sum))
print()

# 2. Maximum value in each row
print("Max in each row:")
print(apply_df.apply(max, axis=1))
print()

# 3. Double values in column A
print("Column A doubled:")
print(apply_df['A'].apply(lambda x: x * 2))
print()

# 4. Add 5 to all values
print("Add 5 to all values:")
print(apply_df.apply(lambda x: x + 5))

Sum of each column:
A      10
B     100
C    1000
dtype: int64

Max in each row:
0    100
1    200
2    300
3    400
dtype: int64

Column A doubled:
0    2
1    4
2    6
3    8
Name: A, dtype: int64

Add 5 to all values:
   A   B    C
0  6  15  105
1  7  25  205
2  8  35  305
3  9  45  405

## Advanced Indexing

Indices are a powerful feature in Pandas that distinguish it from simple arrays. This section covers advanced index operations including basic manipulation and hierarchical indexing.

### Index Manipulation

Let's explore index operations such as resetting and customizing indices.

In [46]:
df

                   W         X         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

In [47]:
# Reset to default 0,1...n index
df.reset_index()

       index         W         X         Y         Z
0 2025-09-01  0.496714 -0.138264  0.647689  1.523030
1 2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2 2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
3 2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
4 2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

In [48]:
newind = 'CA NY WY OR CO'.split()

In [49]:
df['States'] = newind

In [50]:
df

                   W         X         Y         Z States
2025-09-01  0.496714 -0.138264  0.647689  1.523030     CA
2025-09-02 -0.234153 -0.234137  1.579213  0.767435     NY
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730     WY
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288     OR
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304     CO

In [51]:
df.set_index('States')

               W         X         Y         Z
States
CA      0.496714 -0.138264  0.647689  1.523030
NY     -0.234153 -0.234137  1.579213  0.767435
WY     -0.469474  0.542560 -0.463418 -0.465730
OR      0.241962 -1.913280 -1.724918 -0.562288
CO     -1.012831  0.314247 -0.908024 -1.412304

In [52]:
df

                   W         X         Y         Z States
2025-09-01  0.496714 -0.138264  0.647689  1.523030     CA
2025-09-02 -0.234153 -0.234137  1.579213  0.767435     NY
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730     WY
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288     OR
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304     CO

In [53]:
df.set_index('States',inplace=True)

In [54]:
df

               W         X         Y         Z
States
CA      0.496714 -0.138264  0.647689  1.523030
NY     -0.234153 -0.234137  1.579213  0.767435
WY     -0.469474  0.542560 -0.463418 -0.465730
OR      0.241962 -1.913280 -1.724918 -0.562288
CO     -1.012831  0.314247 -0.908024 -1.412304

In [55]:
### EXERCISE: Working with Indices
#
# Create a DataFrame:
idx_df = pd.DataFrame({
    'Value': [10, 20, 30, 40],
    'Category': ['A', 'B', 'A', 'C']
}, index=[100, 200, 300, 400])
#
# Tasks:
# 1. Display the DataFrame
# 2. Reset the index to default (0, 1, 2, 3)
# 3. Set 'Category' as the new index
# 4. Display the final DataFrame
#
### Your code starts here:





### Your code ends here.

In [56]:
# Solution

idx_df = pd.DataFrame({
    'Value': [10, 20, 30, 40],
    'Category': ['A', 'B', 'A', 'C']
}, index=[100, 200, 300, 400])

# 1. Display the DataFrame
print("Original DataFrame:")
print(idx_df)
print()

# 2. Reset index
idx_df = idx_df.reset_index(drop=True)
print("After reset_index:")
print(idx_df)
print()

# 3. Set Category as index
idx_df = idx_df.set_index('Category')

# 4. Display final DataFrame
print("With Category as index:")
print(idx_df)

Original DataFrame:
     Value Category
100     10        A
200     20        B
300     30        A
400     40        C

After reset_index:
   Value Category
0     10        A
1     20        B
2     30        A
3     40        C

With Category as index:
          Value
Category
A            10
B            20
A            30
C            40

### Multi-Index and Index Hierarchy

**Hierarchical Indexing** (or **MultiIndex**) allows multiple levels of row or column labels in a DataFrame. This is very useful for working with grouped or multidimensional data, such as time series across multiple categories or nested groupings.

**When to use MultiIndex:**

- Working with panel data (e.g., multiple time series)
- Hierarchical groupings (e.g., Country > State > City)
- Multi-dimensional data that doesn't fit well in a flat table

Let's create a quick example using `pd.MultiIndex.from_tuples()`.

### Creating multi-level index

In [57]:
# Create index levels for MultiIndex
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]

# In Python, zip() combines two or more lists element-by-element into tuples
# Example:
#   list1 = [1, 2, 3, 4]
#   list2 = ['a', 'b']
#   list(zip(list1, list2)) => [(1, 'a'), (2, 'b')]

hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [60]:
hier_index     # A MultiIndex created from tuples

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

### Creating MultiIndex DataFrame

Pass the hier_index to index parameter; also add columns.

In [62]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1 -1.478522 -0.719844
   2 -0.460639  1.057122
   3  0.343618 -1.763040
G2 1  0.324084 -0.385082
   2 -0.676922  0.611676
   3  1.031000  0.931280

Now let's show how to index this! For index hierarchy we use **df.loc[ ]**, if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [63]:
df.loc['G1']

          A         B
1 -1.478522 -0.719844
2 -0.460639  1.057122
3  0.343618 -1.763040

In [64]:
df.loc['G1'].loc[1]

A   -1.478522
B   -0.719844
Name: 1, dtype: float64

In [65]:
df.loc['G2'].loc[2]['B']

np.float64(0.6116762888408679)

### Changing group names

In [66]:
df.index.names

FrozenList([None, None])

In [67]:
df.index.names = ['Group','Num']

In [68]:
df

                  A         B
Group Num
G1    1   -1.478522 -0.719844
      2   -0.460639  1.057122
      3    0.343618 -1.763040
G2    1    0.324084 -0.385082
      2   -0.676922  0.611676
      3    1.031000  0.931280

### .xs( ) method

The `.xs()` method (short for **cross-section**) is a convenient way to select rows or columns from a Pandas DataFrame, especially when working with **MultiIndex** objects. It works like a shortcut for slicing.

In [69]:
df.xs('G1')

            A         B
Num
1   -1.478522 -0.719844
2   -0.460639  1.057122
3    0.343618 -1.763040

In [70]:
df.xs(1, level='Num')

              A         B
Group
G1    -1.478522 -0.719844
G2     0.324084 -0.385082

**Note:** MultiIndex is an advanced topic that you'll encounter more in later sections on grouping and aggregation. The examples above are for demonstration purposes. As you work with more complex datasets, you'll find MultiIndex particularly useful for hierarchical data analysis.

## Performance Tips and Best Practices

Understanding how Pandas handles data internally can help you write more efficient code.

### Copy vs View

When you slice or select data from a DataFrame, Pandas sometimes returns a **view** (reference to original data) and sometimes a **copy** (new data). This affects both performance and behavior.

In [ ]:
# Create a sample DataFrame
perf_df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print("Original DataFrame:")
print(perf_df)

In [ ]:
# Selecting a column returns a view (changes affect original)
col_a = perf_df['A']
print("\nColumn A:", col_a)
print("Is it a view? Changes to col_a affect perf_df")

In [ ]:
# Use .copy() to create an independent copy
col_a_copy = perf_df['A'].copy()
col_a_copy[0] = 999

print("\nAfter modifying col_a_copy:")
print("Original DataFrame A column:", perf_df['A'][0])  # Unchanged
print("Copy:", col_a_copy[0])  # Changed

**Best Practice:** Use `.copy()` when you want to ensure your modifications don't affect the original DataFrame.

### Memory Usage

Use `.memory_usage()` to check how much memory your DataFrame is using.

In [ ]:
# Check memory usage in bytes
perf_df.memory_usage()

In [ ]:
# Get total memory in KB or MB
total_bytes = perf_df.memory_usage(deep=True).sum()
print(f"Total memory: {total_bytes} bytes")
print(f"Total memory: {total_bytes / 1024:.2f} KB")

### Vectorization vs Iteration

**Always prefer vectorized operations over loops** when working with DataFrames. Vectorized operations are much faster.

In [ ]:
# SLOW: Iterating through rows (avoid this!)
# for index, row in df.iterrows():
#     df.at[index, 'new_col'] = row['A'] * 2

# FAST: Vectorized operation
perf_df['A_doubled'] = perf_df['A'] * 2
print(perf_df)

**Key Takeaways:**

1. Use `.copy()` when you need an independent copy of data
2. Check `.memory_usage()` for large datasets
3. Prefer vectorized operations over loops
4. Use `.at[]` and `.iat[]` for single-value access instead of `.loc[]` and `.iloc[]`
5. Chain operations carefully to avoid unintended side effects