# Pandas DataFrames

DataFrames are the core data structure in Pandas, modeled after similar structures in the **R** programming language. A DataFrame is a **two-dimensional, labeled data structure** that can be thought of as:

- A **collection of Series objects** combined into a single table, all sharing the same index
- A **spreadsheet or SQL table** with rows and columns
- A **dictionary of Series**, where each column is a Series with a shared index

**Key Features of DataFrames**

- **Labeled axes**: Both rows (index) and columns have labels, making data access intuitive and explicit
- **Heterogeneous data**: Different columns can contain different data types (integers, floats, strings, dates, etc.)
- **Size-mutable**: You can insert and delete columns
- **Powerful operations**: Built-in methods for filtering, grouping, merging, reshaping, and statistical analysis
- **Alignment** of data based on labels
- **Missing data** handling (see [0404-missing-data.ipynb](0404-missing-data.ipynb) for details)
- **Rich I/O tools** for reading/writing various formats (CSV, Excel, SQL, JSON, etc.)

**Why DataFrames?**

While NumPy arrays are excellent for numerical computation, DataFrames offer several advantages:

- **Column names** instead of just numeric indices
- **Mixed data types** in different columns
- Accessing and selecting data
- Modifying DataFrames (adding/removing columns and rows)
- Sorting and filtering
- Working with indices, including MultiIndex

**What You'll Learn**

In this notebook, we'll explore:

1. Creating DataFrames from various sources
2. DataFrame attributes and methods
3. Indexing and selecting data
4. Sorting and filtering
5. Working with indices, including MultiIndex
6. Performance tips and best practices

**Note:** Missing data handling is covered in detail in notebook [0404-missing-data.ipynb](0404-missing-data.ipynb).

Let's use Pandas to explore how DataFrames work!

**Additional Resources:**
- [Official Pandas Documentation](https://pandas.pydata.org/docs/)
- [DataFrame API Reference](https://pandas.pydata.org/docs/reference/frame.html)
- [10 Minutes to Pandas](https://pandas.pydata.org/docs/user_guide/10min.html)

In [78]:
import numpy as np
import pandas as pd
import sqlite3

## Reading Datasets

Following the instruction in [Handling Dataset](https://thinkdsm.org/chapters/04-pandas/02-pd-handle-datasets.html), you are able to access the dataset files in your data directory.

In [79]:
# Read CSV file - both forward slashes (/) work on Windows, macOS, and Linux

df_sample = pd.read_csv("../../data/data.csv")
df_sample

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

In [80]:
df_sample.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  339 non-null    object
 1   Pulse     339 non-null    object
 2   Maxpulse  339 non-null    object
 3   Calories  329 non-null    object
dtypes: object(4)
memory usage: 10.7+ KB

In [81]:
df_sample      # Default view is table-like
               # Pandas will show first 5 and last 5 rows (10 total) by default
               # The shape information is displayed at the bottom

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

Sometimes, you need to see more than the default output. You use the pd.options.display.max_rows attribute.

In [82]:
pd.options.display.max_rows = 50     # Set max_rows display limit

In [83]:
### EXERCISE: Reading CSV Files
#
# Using the data/baby.csv file:
# 1. Read the CSV file into a DataFrame called baby_df
# 2. Display the first 7 rows
# 3. Display the last 3 rows
# 4. Check the shape of the DataFrame
# 5. Get the column names
#
### Your code starts here:





### Your code ends here.

## DataFrame Attributes & Methods

DataFrames have many useful attributes and methods that help us understand the structure and content of our data. Let's explore the most commonly used ones.

In [84]:
# Get the dimensions of the DataFrame (rows, columns)
df_sample.shape

(339, 4)

In [85]:
# Get the number of rows
len(df_sample)

339

In [86]:
# Get all column names
df_sample.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

### Data Types

### Statistical Summary

In [87]:
# Get statistical summary of numeric columns
df_sample.describe()

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10

In [88]:
# View first 5 rows (default)
df_sample.head()

  Duration Pulse Maxpulse Calories
0       60   110      130    409.1
1       60   117      145      479
2       60   103      135      340
3       45   109      175    282.4
4       45   117      148      406

### Reading from SQLite Databases

Beyond CSV files, Pandas can read from many data sources. Let's explore loading data from a SQLite database that we've used in previous SQL activities. You'll appreciate how convenient Pandas makes this!

To connect to a SQLite database, we:
1. Import the sqlite3 library (part of Python's standard library)
2. Connect to the database using `sqlite3.connect()`
3. Use the Pandas function `read_sql_query()` to execute your query
4. Close the connection using the `close()` function (or use `with` statement)

In [89]:
import sqlite3
conn = sqlite3.connect('../../data/chinook.db')

df_customer = pd.read_sql_query("SELECT * FROM customer;", conn)
df_customer.head()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4

In [90]:
# BETTER PRACTICE: Use 'with' statement to automatically close connection
# The 'with' statement ensures the connection is closed even if an error occurs

sql = 'SELECT * FROM Artist LIMIT 10'
with sqlite3.connect("../../data/chinook.db") as conn:
    df_artist = pd.read_sql_query(sql, conn)

df_artist

   ArtistId                  Name
0         1                 AC/DC
1         2                Accept
2         3             Aerosmith
3         4     Alanis Morissette
4         5       Alice In Chains
5         6  Antônio Carlos Jobim
6         7          Apocalyptica
7         8            Audioslave
8         9              BackBeat
9        10          Billy Cobham

In [91]:
# Solution

# 1. Number of rows and columns
print("Shape (rows, columns):", df_artist.shape)
print()

# 2. Data types
print("Data types:")
print(df_artist.dtypes)
print()

# 3. Statistical summary
print("Statistical summary:")
print(df_artist.describe())
print()

# 4. Index values
print("Index:", df_artist.index.tolist())
print()

# 5. Total elements
print("Total elements:", df_artist.size)

Shape (rows, columns): (10, 2)

Data types:
ArtistId     int64
Name        object
dtype: object

Statistical summary:
       ArtistId
count  10.00000
mean    5.50000
std     3.02765
min     1.00000
25%     3.25000
50%     5.50000
75%     7.75000
max    10.00000

Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

Total elements: 20

In [92]:
# Create a date index using pd.date_range()
# This function generates a range of dates similar to how range() generates numbers

# dates = pd.date_range()     # Shift+Tab to see documentation
dates = pd.date_range("20250901", periods=6)

In [93]:
# Check the data type: it's a DatetimeIndex object

type(dates)

pandas.core.indexes.datetimes.DatetimeIndex

In [94]:
# Create a DataFrame using pd.DataFrame()
# pd.DataFrame    # Shift+Tab to see documentation

# Set random seed for reproducibility (ensures same "random" numbers each time)
np.random.seed(42)

df_dates = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

In [95]:
# Verify the type: this confirms we have a DataFrame object

type(df_dates)

pandas.core.frame.DataFrame

In [96]:
# Solution

# Create the DataFrame
students_df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [20, 22, 21, 23],
    'City': ['NYC', 'LA', 'Chicago', 'Boston'],
    'Score': [85, 92, 67, 78]
}, index=['S1', 'S2', 'S3', 'S4'])

# 1. Display the DataFrame
print("Students DataFrame:")
print(students_df)
print()

# 2. Select Name and Score columns
print("Name and Score:")
print(students_df[['Name', 'Score']])
print()

# 3. Add Pass column
students_df['Pass'] = students_df['Score'] >= 70
print("With Pass column:")
print(students_df)

Students DataFrame:
       Name  Age     City  Score
S1    Alice   20      NYC     85
S2      Bob   22       LA     92
S3  Charlie   21  Chicago     67
S4    Diana   23   Boston     78

Name and Score:
       Name  Score
S1    Alice     85
S2      Bob     92
S3  Charlie     67
S4    Diana     78

With Pass column:
       Name  Age     City  Score   Pass
S1    Alice   20      NYC     85   True
S2      Bob   22       LA     92   True
S3  Charlie   21  Chicago     67  False
S4    Diana   23   Boston     78   True

In [97]:
### Create DataFrame with employee salary data (in thousands)
### This is more meaningful than random numbers

df_sal = pd.DataFrame({
    'Salary': [75, 82, 68, 91, 55],
    'Bonus': [8.5, 12.3, 5.2, 15.8, 3.1],
    'Years': [3, 5, 2, 7, 1],
    'Rating': [4.2, 4.7, 3.8, 4.9, 3.5]
}, index=['Alice', 'Bob', 'Charlie', 'Diana', 'Eve'])

df_sal

         Salary  Bonus  Years  Rating
Alice        75    8.5      3     4.2
Bob          82   12.3      5     4.7
Charlie      68    5.2      2     3.8
Diana        91   15.8      7     4.9
Eve          55    3.1      1     3.5

In [98]:
### Use bracket notation to select a single column

df_sal['Salary']

Alice      75
Bob        82
Charlie    68
Diana      91
Eve        55
Name: Salary, dtype: int64

#### Multiple Columns
Pass a list of column names to select multiple columns. The result is a DataFrame.

DataFrame Columns are just Series

### Row Selection

Accessing DataFrame rows with **loc** (label-based) and **iloc** (position-based).

#### Using .loc[ ] - Label-based indexing

In [99]:
ser = df_sal.loc['Alice']
type(ser)

pandas.core.series.Series

In [100]:
### Get the third row (index position 2) - Charlie's data
df_sal.iloc[2]

Salary    68.0
Bonus      5.2
Years      2.0
Rating     3.8
Name: Charlie, dtype: float64

In [101]:
### Get first two rows (positions 0 and 1)
df_sal.iloc[0:2]

       Salary  Bonus  Years  Rating
Alice      75    8.5      3     4.2
Bob        82   12.3      5     4.7

In [102]:
### Get value at row position 0, column position 0 (Alice's Salary)
df_sal.iloc[0, 0]

np.int64(75)

In [103]:
### Get first two rows and first two columns
df_sal.iloc[0:2, 0:2]

       Salary  Bonus
Alice      75    8.5
Bob        82   12.3

In [104]:
### Get all rows, but only columns at positions 0 and 2 (Salary and Rating)
df_sal.iloc[:, [0, 2]]

         Salary  Years
Alice        75      3
Bob          82      5
Charlie      68      2
Diana        91      7
Eve          55      1

In [105]:
df_sal

         Salary  Bonus  Years  Rating
Alice        75    8.5      3     4.2
Bob          82   12.3      5     4.7
Charlie      68    5.2      2     3.8
Diana        91   15.8      7     4.9
Eve          55    3.1      1     3.5

In [106]:
### Get Salary and Rating for Alice and Bob
df_sal.loc[['Alice','Bob'],['Salary','Rating']]

       Salary  Rating
Alice      75     4.2
Bob        82     4.7

In [107]:
# Using .at[] for fast label-based access to a single value
df_sal.at['Alice', 'Salary']

np.int64(75)

In [108]:
# Performance comparison: .at[] is faster than .loc[] for single values
# .loc[] works, but .at[] is optimized for this use case
print("Using .loc[]:", df_sal.loc['Bob', 'Rating'])
print("Using .at[]:", df_sal.at['Bob', 'Rating'])

Using .loc[]: 4.7
Using .at[]: 4.7

In [109]:
df_sal

         Salary  Bonus  Years  Rating
Alice        75    8.5      3     4.2
Bob          82   12.3      5     4.7
Charlie      68    5.2      2     3.8
Diana        91   15.8      7     4.9
Eve          55    3.1      1     3.5

In [110]:
df_sal[df_sal>0]

         Salary  Bonus  Years  Rating
Alice        75    8.5      3     4.2
Bob          82   12.3      5     4.7
Charlie      68    5.2      2     3.8
Diana        91   15.8      7     4.9
Eve          55    3.1      1     3.5

In [111]:
### Get Years for employees with Salary > 70
df_sal[df_sal['Salary']>70]['Years']

Alice    3
Bob      5
Diana    7
Name: Years, dtype: int64

In [112]:
### BETTER PRACTICE: Use .loc[] for row and column selection together
df_sal.loc[df_sal['Salary']>70, ['Years','Bonus']]

       Years  Bonus
Alice      3    8.5
Bob        5   12.3
Diana      7   15.8

In [113]:
### Combine conditions with & (and) or | (or)
### Each condition must be in parentheses

df_sal[(df_sal['Salary']>70) & (df_sal['Years'] > 2)]

       Salary  Bonus  Years  Rating
Alice      75    8.5      3     4.2
Bob        82   12.3      5     4.7
Diana      91   15.8      7     4.9

In [114]:
# Same result as above, but more readable
df_sal.query('Salary > 70 and Years > 2')

       Salary  Bonus  Years  Rating
Alice      75    8.5      3     4.2
Bob        82   12.3      5     4.7
Diana      91   15.8      7     4.9

### Row/Column Operations

In [115]:
### Create a new column: Total Compensation
df_sal['TotalComp'] = df_sal['Salary'] + df_sal['Bonus']

#### Dropping columns

Using the drop function. Note that you have to specify **axis=1** to drop the column label.

**Understanding axis parameter:**
- `axis=0` → operates on **rows** (index) - "go down the rows"
- `axis=1` → operates on **columns** - "go across the columns"

**Mnemonic**: Think of axis as the direction you're moving. axis=0 goes down (rows), axis=1 goes across (columns).

In [116]:
# Not modified! Most DataFrame operations are not in-place by default
df_sal

         Salary  Bonus  Years  Rating  TotalComp
Alice        75    8.5      3     4.2       83.5
Bob          82   12.3      5     4.7       94.3
Charlie      68    5.2      2     3.8       73.2
Diana        91   15.8      7     4.9      106.8
Eve          55    3.1      1     3.5       58.1

In [117]:
df_sal.drop('TotalComp',axis=1,inplace=True)

df_sal

         Salary  Bonus  Years  Rating
Alice        75    8.5      3     4.2
Bob          82   12.3      5     4.7
Charlie      68    5.2      2     3.8
Diana        91   15.8      7     4.9
Eve          55    3.1      1     3.5

#### Dropping rows

To drop rows, use the `.drop()` method with **axis=0** (or no axis parameter since axis=0 is the default).

You can drop rows by specifying their index labels.

In [ ]:
# Drop a single row by index label (returns a new DataFrame)
df_sal.drop('Charlie')

In [ ]:
# Drop multiple rows (pass a list of index labels)
df_sal.drop(['Alice', 'Eve'], axis=0)

In [ ]:
# Use inplace=True to modify the original DataFrame
# df_sal.drop('Bob', axis=0, inplace=True)

# Note: Commented out to preserve df_sal for other examples

## DataFrame Selection and Indexing

This section covers various methods for selecting and indexing data in DataFrames.

In [118]:
### EXERCISE: DataFrame Indexing Practice
#
# Given the following sales data:
sales_data = pd.DataFrame({
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam'],
    'Q1': [50, 200, 150, 75, 90],
    'Q2': [65, 210, 160, 80, 95],
    'Q3': [70, 190, 155, 85, 100],
    'Q4': [80, 220, 170, 90, 110]
}, index=['P1', 'P2', 'P3', 'P4', 'P5'])
#
# Tasks:
# 1. Select the Q2 and Q4 columns
# 2. Select rows P2 and P4
# 3. Select Q3 sales for rows P1, P3, and P5 (should return a Series)
# 4. Add a new column 'Total' that sums Q1 through Q4 (Tip: use .sum(axis=1))
# 5. Drop the Q1 column (without modifying the original DataFrame)
#
# Hint: Use double brackets [[]] for selecting multiple columns
#
### Your code starts here:





### Your code ends here.

In [ ]:
# Solution

# 1. Select the Q2 and Q4 columns
print("Q2 and Q4 columns:")
print(sales_data[['Q2', 'Q4']])
print()

# 2. Select rows P2 and P4
print("Rows P2 and P4:")
print(sales_data.loc[['P2', 'P4']])
print()

# 3. Select Q3 sales for rows P1, P3, and P5
print("Q3 sales for P1, P3, P5:")
print(sales_data.loc[['P1', 'P3', 'P5'], 'Q3'])
print()

# 4. Add a new column 'Total' that sums Q1 through Q4
sales_data_with_total = sales_data.copy()
sales_data_with_total['Total'] = sales_data_with_total[['Q1', 'Q2', 'Q3', 'Q4']].sum(axis=1)
print("With Total column:")
print(sales_data_with_total)
print()

# 5. Drop the Q1 column
print("Without Q1 column:")
print(sales_data.drop('Q1', axis=1))

## DataFrame Operations

This section covers common DataFrame manipulation operations including sorting, handling duplicates, and renaming.

In [119]:
### Recreate DataFrame with random data for sorting examples
np.random.seed(42)
dates = pd.date_range('20250901', periods=5)
df_sort = pd.DataFrame(np.random.randn(5, 4), index=dates, columns=list('WXYZ'))
df_sort

                   W         X         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

In [120]:
# Sort by a single column (ascending)
df_sort.sort_values(by='W')

                   W         X         Y         Z
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-01  0.496714 -0.138264  0.647689  1.523030

In [121]:
# Sort by multiple columns
df_sort.sort_values(by=['W', 'Z'])

                   W         X         Y         Z
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-01  0.496714 -0.138264  0.647689  1.523030

In [122]:
# Sort by index labels
df_sort.sort_index()

                   W         X         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

In [123]:
### EXERCISE: Sorting DataFrames
#
# Create a DataFrame:
sort_df = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana'],
    'Age': [25, 30, 22, 28],
    'Score': [85, 92, 78, 92]
})
#
# Tasks:
# 1. Sort by Age in ascending order
# 2. Sort by Score in descending order
# 3. Sort by Score (descending), then by Age (ascending)
# 4. Sort by index
#
### Your code starts here:





### Your code ends here.

### Handling Duplicates

DataFrames often contain duplicate rows. Pandas provides methods to identify and remove them.

In [124]:
# Create a DataFrame with duplicate rows for demonstration
df_dup = pd.DataFrame({
    'A': [1, 2, 2, 3, 3, 4],
    'B': [10, 20, 20, 30, 30, 40],
    'C': ['x', 'y', 'y', 'z', 'w', 'v']
})
df_dup

   A   B  C
0  1  10  x
1  2  20  y
2  2  20  y
3  3  30  z
4  3  30  w
5  4  40  v

In [125]:
# Check for duplicate rows (returns boolean Series)
df_dup.duplicated()

0    False
1    False
2     True
3    False
4    False
5    False
dtype: bool

In [126]:
# Drop duplicates based on specific columns
df_dup.drop_duplicates(subset=['A'])

   A   B  C
0  1  10  x
1  2  20  y
3  3  30  z
5  4  40  v

In [127]:
# Solution

dup_df = pd.DataFrame({
    'A': [1, 2, 2, 3, 3, 4],
    'B': [10, 20, 20, 30, 30, 40],
    'C': ['x', 'y', 'y', 'z', 'w', 'v']
})

# 1. Display the DataFrame
print("Original DataFrame:")
print(dup_df)
print()

# 2. Check for duplicates
print("Duplicate rows:")
print(dup_df.duplicated())
print()

# 3. Remove all duplicates
print("After removing all duplicates:")
print(dup_df.drop_duplicates())
print()

# 4. Remove duplicates based on column A
print("After removing duplicates in column A:")
print(dup_df.drop_duplicates(subset=['A']))

Original DataFrame:
   A   B  C
0  1  10  x
1  2  20  y
2  2  20  y
3  3  30  z
4  3  30  w
5  4  40  v

Duplicate rows:
0    False
1    False
2     True
3    False
4    False
5    False
dtype: bool

After removing all duplicates:
   A   B  C
0  1  10  x
1  2  20  y
3  3  30  z
4  3  30  w
5  4  40  v

After removing duplicates in column A:
   A   B  C
0  1  10  x
1  2  20  y
3  3  30  z
5  4  40  v

### Renaming Columns and Index

Pandas provides the `.rename()` method to rename columns and index labels. This is useful when you need more descriptive names or want to standardize naming conventions.

In [128]:
df_sort

                   W         X         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

In [129]:
# Rename columns
df_sort.rename(columns={'W': 'Weight', 'X': 'X_coord'})

              Weight   X_coord         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

In [130]:
### EXERCISE: Renaming DataFrame Elements
#
# Create a DataFrame:
rename_df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8, 9]
}, index=['row1', 'row2', 'row3'])
#
# Tasks:
# 1. Display the original DataFrame
# 2. Rename column 'a' to 'Alpha' and 'b' to 'Beta'
# 3. Rename the index 'row1' to 'R1' and 'row2' to 'R2'
# 4. Display the renamed DataFrame
#
### Your code starts here:





### Your code ends here.

In [131]:
# Solution

rename_df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [4, 5, 6],
    'c': [7, 8, 9]
}, index=['row1', 'row2', 'row3'])

# 1. Display the original DataFrame
print("Original DataFrame:")
print(rename_df)
print()

# 2. Rename columns 'a' to 'Alpha' and 'b' to 'Beta'
rename_df = rename_df.rename(columns={'a': 'Alpha', 'b': 'Beta'})

# 3. Rename index 'row1' to 'R1' and 'row2' to 'R2'
rename_df = rename_df.rename(index={'row1': 'R1', 'row2': 'R2'})

# 4. Display the renamed DataFrame
print("Renamed DataFrame:")
print(rename_df)

Original DataFrame:
      a  b  c
row1  1  4  7
row2  2  5  8
row3  3  6  9

Renamed DataFrame:
      Alpha  Beta  c
R1        1     4  7
R2        2     5  8
row3      3     6  9

## Applying Functions with `.apply()`

The `.apply()` method is a powerful tool that allows you to apply a function along an axis of the DataFrame (rows or columns). This is useful for transformations, calculations, and custom operations.

The syntax for `.apply()` is:

```python
DataFrame.apply(func, axis=0, raw=False, result_type=None, args=(), **kwargs)
```

**Parameters:**
- `func`: Function to apply to each column or row
- `axis`: {0 or 'index', 1 or 'columns'}, default 0
  - 0 or 'index': apply function to each column
  - 1 or 'columns': apply function to each row
- `raw`: bool, default False. If False, passes each row/column as a Series to the function. If True, passes ndarray
- `result_type`: {'expand', 'reduce', 'broadcast', None}, default None
- `args`: tuple, positional arguments to pass to func
- `**kwargs`: additional keyword arguments to pass to func

**Returns:** Series or DataFrame

**Performance Note:** For simple operations like arithmetic or comparisons, vectorized operations are usually faster than `.apply()`. Use `.apply()` when you need to apply a complex function that can't be vectorized.

```python
# Vectorized (faster): df['A'] * 2
# Using apply (slower): df['A'].apply(lambda x: x * 2)
```

In [132]:
# Apply a function to each column (axis=0, default)
print(df_sort.apply(np.sum))
print(type(df_sort.apply(np.sum)))

W   -0.977782
X   -1.428874
Y   -0.869458
Z   -0.149856
dtype: float64
<class 'pandas.core.series.Series'>

In [133]:
# Apply a custom function (double each value)
df_sort.apply(lambda x: x * 2)

                   W         X         Y         Z
2025-09-01  0.993428 -0.276529  1.295377  3.046060
2025-09-02 -0.468307 -0.468274  3.158426  1.534869
2025-09-03 -0.938949  1.085120 -0.926835 -0.931460
2025-09-04  0.483925 -3.826560 -3.449836 -1.124575
2025-09-05 -2.025662  0.628495 -1.816048 -2.824607

In [134]:
### EXERCISE: Applying Functions
#
# Create a DataFrame:
apply_df = pd.DataFrame({
    'A': [1, 2, 3, 4],
    'B': [10, 20, 30, 40],
    'C': [100, 200, 300, 400]
})
#
# Tasks:
# 1. Apply a function to get the sum of each column
# 2. Apply a function to get the maximum value in each row
# 3. Apply a lambda function to double all values in column A
# 4. Apply a custom function that adds 5 to all values
#
### Your code starts here:





### Your code ends here.

In [ ]:
# Solution

# 1. Apply a function to get the sum of each column
print("Sum of each column:")
print(apply_df.apply(np.sum))
print()

# 2. Apply a function to get the maximum value in each row
print("Maximum value in each row:")
print(apply_df.apply(np.max, axis=1))
print()

# 3. Apply a lambda function to double all values in column A
print("Column A doubled:")
print(apply_df['A'].apply(lambda x: x * 2))
print()

# 4. Apply a custom function that adds 5 to all values
def add_five(x):
    return x + 5

print("All values plus 5:")
print(apply_df.apply(add_five))

## Advanced Indexing

Indices are a powerful feature in Pandas that distinguish it from simple arrays. This section covers advanced index operations including basic manipulation and hierarchical indexing.

In [135]:
df_sort

                   W         X         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

### Changing Index

You can directly assign a new index to a DataFrame by setting the `.index` attribute. The new index must have the same length as the number of rows.

In [136]:
### so this is original df_sort
df_sort

                   W         X         Y         Z
2025-09-01  0.496714 -0.138264  0.647689  1.523030
2025-09-02 -0.234153 -0.234137  1.579213  0.767435
2025-09-03 -0.469474  0.542560 -0.463418 -0.465730
2025-09-04  0.241962 -1.913280 -1.724918 -0.562288
2025-09-05 -1.012831  0.314247 -0.908024 -1.412304

In [152]:
newind = 'CA NY WY OR CO'.split()

In [153]:
df_sort.index = newind

In [154]:
df_sort

           W         X         Y         Z
CA  0.496714 -0.138264  0.647689  1.523030
NY -0.234153 -0.234137  1.579213  0.767435
WY -0.469474  0.542560 -0.463418 -0.465730
OR  0.241962 -1.913280 -1.724918 -0.562288
CO -1.012831  0.314247 -0.908024 -1.412304

In [ ]:
### EXERCISE: Index Manipulation
#
# Create a DataFrame:
idx_df = pd.DataFrame({
    'Value': [10, 20, 30, 40],
    'Category': ['A', 'B', 'A', 'C']
}, index=[100, 200, 300, 400])
#
# Tasks:
# 1. Display the original DataFrame
# 2. Reset the index (drop the old index)
# 3. Set 'Category' as the new index
# 4. Display the final DataFrame
#
### Your code starts here:





### Your code ends here.

In [140]:
# Solution

idx_df = pd.DataFrame({
    'Value': [10, 20, 30, 40],
    'Category': ['A', 'B', 'A', 'C']
}, index=[100, 200, 300, 400])

# 1. Display the DataFrame
print("Original DataFrame:")
print(idx_df)
print()

# 2. Reset index
idx_df = idx_df.reset_index(drop=True)
print("After reset_index:")
print(idx_df)
print()

# 3. Set Category as index
idx_df = idx_df.set_index('Category')

# 4. Display final DataFrame
print("With Category as index:")
print(idx_df)

Original DataFrame:
     Value Category
100     10        A
200     20        B
300     30        A
400     40        C

After reset_index:
   Value Category
0     10        A
1     20        B
2     30        A
3     40        C

With Category as index:
          Value
Category
A            10
B            20
A            30
C            40

### Multi-level index

In [141]:
# Create a hierarchical index using MultiIndex.from_tuples()
# Each tuple represents (outer_level, inner_level)
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2']
inside = [1, 2, 3, 1, 2, 3]
hier_index = pd.MultiIndex.from_arrays([outside, inside], names=['Group', 'Num'])
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           names=['Group', 'Num'])

In [142]:
df_multi = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df_multi

                  A         B
Group Num
G1    1    1.465649 -0.225776
      2    0.067528 -1.424748
      3   -0.544383  0.110923
G2    1   -1.150994  0.375698
      2   -0.600639 -0.291694
      3   -0.601707  1.852278

In [143]:
df_multi.loc['G1']

            A         B
Num
1    1.465649 -0.225776
2    0.067528 -1.424748
3   -0.544383  0.110923

In [144]:
df_multi.loc['G2'].loc[2]['B']

np.float64(-0.2916937497932768)

In [145]:
df_multi.index.names

FrozenList(['Group', 'Num'])

In [146]:
df_multi

                  A         B
Group Num
G1    1    1.465649 -0.225776
      2    0.067528 -1.424748
      3   -0.544383  0.110923
G2    1   -1.150994  0.375698
      2   -0.600639 -0.291694
      3   -0.601707  1.852278

The `.xs()` method (short for **cross-section**) is a convenient way to select rows or columns from a Pandas DataFrame, especially when working with **MultiIndex** objects. It works like a shortcut for slicing.

In [147]:
df_multi.xs(1, level='Num')

              A         B
Group
G1     1.465649 -0.225776
G2    -1.150994  0.375698

## Performance Tips and Best Practices

Understanding how Pandas handles data internally can help you write more efficient code.

In [148]:
# Create a sample DataFrame
perf_df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6]})
print("Original DataFrame:")
print(perf_df)

Original DataFrame:
   A  B
0  1  4
1  2  5
2  3  6

In [149]:
# Use .copy() to create an independent copy
col_a_copy = perf_df['A'].copy()
col_a_copy[0] = 999

print("\nAfter modifying col_a_copy:")
print("Original DataFrame A column:", perf_df['A'][0])  # Unchanged
print("Copy:", col_a_copy[0])  # Changed

After modifying col_a_copy:
Original DataFrame A column: 1
Copy: 999

### Memory Usage

Use `.memory_usage()` to check how much memory your DataFrame is using.

In [150]:
# Get total memory in KB or MB
total_bytes = perf_df.memory_usage(deep=True).sum()
print(f"Total memory: {total_bytes} bytes")
print(f"Total memory: {total_bytes / 1024:.2f} KB")

Total memory: 180 bytes
Total memory: 0.18 KB

In [151]:
# SLOW: Iterating through rows (avoid this!)
# for index, row in df.iterrows():
#     df.at[index, 'new_col'] = row['A'] * 2

# FAST: Vectorized operation
perf_df['A_doubled'] = perf_df['A'] * 2
print(perf_df)

   A  B  A_doubled
0  1  4          2
1  2  5          4
2  3  6          6