# h04 Pandas - Questions
In this homework, you will do:
- Python review: for loop & data collection operations
- NumPy array operations
- Pandas Operations

**Academic honor**:
1. Academic honor is important. Do your work, learn, **DON'T CHEAT!** 
2. <font color='darkred'>**Use AI to LEARN, not to cheat**. **DO NOT do copy-and-paste**</font>. 
3. Collaboration and using resources are encouraged, but DO NOT directly share answers.

In [ ]:
### import libraries

##### change me #####              ### import numpy
##### change me #####             ### import pandas

## 1. Programming Review

- All the programming knowledge (e.g., data types, data structure...) and skills (e.g., loops, functions) are covered in the programming classes you took previously. 
- This is a review.

### 1.1. for loop with list

In [ ]:
### create a list following the instructions below

lst1 = ##### change me #####        ### use the range() function to create the a list called lst1
lst2 = ##### change me #####        ### create an empty list, lst2, to save the results  
for ##### change me #####           ### a for loop to loop through the elements in lst1 
    ##### change me #####           ### if the element is even
    ##### change me #####           ### append the square of the element to lst2
                                    ###
print(##### change me #####)        ### print the results in lst2; use the end= parameter when printing

[4, 16, 36, 64]

### 1.2. for loop with list comprehension

In [ ]:
### create a list (lst3) using list comprehension following the instructions below

lst3 = ##### change me #####        ### create a list comprehension to generate the same results as lst2
print(lst3, end=" ")                ### print the results in lst3; use the end= parameter when printing

[4, 16, 36, 64]

### 1.3. dictionary

In [ ]:
### create a dictionary, call it fruit_price, containing 
### apple, banana, cherry as keys with lists of prices (values)

fruit_price = {
    ##### change me #####       ### the price of apple is a list [3, 2, 3]
    ##### change me #####       ### the price of banana is a list [4, 5, 4]
    ##### change me #####       ### the price of cherry is a list [5, 5, 5]
}

print(fruit_price['banana'])   ### print the price of banana

[4, 5, 4]

## 2. NumPy Array Operations

### 2.1 NumPy Vector

In [ ]:
### create a numpy array, call it arr1, from the list lst1
arr1 = ##### change me #####        ### create a numpy array from lst1
print(##### change me #####)        ### print the array
print(##### change me #####)        ### print the data type of the array
##### change me #####               ### print the dtype of the array elements
##### change me #####               ### print the number of dimensions of the array
##### change me #####               ### print the shape of the array
##### change me #####               ### print the element at index 5 (the 6th element)
##### change me #####               ### print the array added to itself
##### change me #####               ### print the array multiplied by 5

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64
1
(9,)
6
[ 2  4  6  8 10 12 14 16 18]
[ 5 10 15 20 25 30 35 40 45]

### 2.2. NumPy Matrix

In [ ]:
### create a numpy vector called v using the arange function
### v should contain integers from 0 to 19 

v = ##### change me #####       ### create vector v
arr2 = ##### change me #####    ### create arr2 to a 4 x 5 matrix use reshape function
print(arr2)                     ### print the 2D array
print(##### change me #####)    ### print the data type of the matrix
print(##### change me #####)    ### print the data type of the array elements
##### change me #####           ### print the number of dimensions of arr2
##### change me #####           ### print the shape of arr2
##### change me #####           ### print a subset of the matrix

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
<class 'numpy.ndarray'>
int64
2
(4, 5)
[[3 4]
 [8 9]]

## 3. Pandas Operations

### 3.1. Pandas Series

In [ ]:
### create a Pandas Series using lst3, call it ser

ser = ##### change me #####     ### create the Pandas Series
print(ser)                      ### print the Series

0     4
1    16
2    36
3    64
dtype: int64

### 3.2. Create Pandas DataFrame

- create a DataFrame from a dictionary

In [ ]:
### create a Pandas DataFrame using dictionary fruit_price, call it df

df = ##### change me #####        ### create the Pandas DataFrame
df

   apple  banana  cherry
0      3       4       5
1      2       5       5
2      3       4       5

In [ ]:
### indexing and selection in DataFrame df
print(##### change me #####)             ### select the column 'banana'
print(##### change me #####) ### select columns 'banana' and 'cherry'
print(##### change me #####)                ### select the first row using loc
print(##### change me #####)              ### select the first two rows using loc
print(##### change me #####)               ### select the first row using iloc
print(##### change me #####)             ### select the first two rows using iloc

0    4
1    5
2    4
Name: banana, dtype: int64
   banana  cherry
0       4       5
1       5       5
2       4       5
apple     3
banana    4
cherry    5
Name: 0, dtype: int64
   apple  banana  cherry
0      3       4       5
1      2       5       5
apple     3
banana    4
cherry    5
Name: 0, dtype: int64
   apple  banana  cherry
0      3       4       5
1      2       5       5

### 3.3. Create Pandas DataFrame

In [ ]:
### create a Pandas DataFrame, call it df, using arr2
### use the following column names: A, B, C, D, E

df = ##### change me #####                                  ### create the DataFrame
print(df)                                                   ### print the DataFrame

    A   B   C   D   E
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

### 3.4. Read File

In [ ]:
### read a file from your data folder into a DataFrame, call it df1

df1 = ##### change me #####         ### read the data file into a DataFrame
print(df1)                                      ### print the DataFrame

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

In [ ]:
### show the first 5 rows of the DataFrame df1 using the head() method

##### change me #####                              ### print the first 5 rows of the DataFrame

  Duration Pulse Maxpulse Calories
0       60   110      130    409.1
1       60   117      145      479
2       60   103      135      340
3       45   109      175    282.4
4       45   117      148      406

In [ ]:
### show the basic information of the DataFrame df1 using the info() method

##### change me #####                                ### print the summary information of the DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 339 entries, 0 to 338
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  339 non-null    object
 1   Pulse     339 non-null    object
 2   Maxpulse  339 non-null    object
 3   Calories  329 non-null    object
dtypes: object(4)
memory usage: 10.7+ KB

In [ ]:
### show the descriptive statistics of the DataFrame df1 using the describe() method

##### change me #####                             ### print the descriptive statistics of the DataFrame

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10

### 3.5. Missing Data

In [23]:
### create a DataFrame, call it df, with missing data
### use the following data

df = pd.DataFrame({                     ### create the DataFrame
    'A' : [ 1, 2, np.nan ],             ### np.nan means "Not a Number", i.e., missing data
    'B' : [ 5, np.nan, np.nan],         
    'C' : [ 1, 2, 3]
    })

In [32]:
print(df)                                     ### print the DataFrame

     A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [ ]:
### detect the missing data in DataFrame df using the isna() method
print(##### change me #####, "\n")          ### detect the missing data in DataFrame df using the isna() method
print(##### change me #####, "\n")          ### print the number of missing data in each column
print(##### change me #####, "\n")          ### fill the missing data with 0 and print the DataFrame

       A      B      C
0  False  False  False
1  False   True  False
2   True   True  False

A    1
B    2
C    0
dtype: int64

     A    B  C
0  1.0  5.0  1
1  2.0  0.0  2
2  0.0  0.0  3

The end