# Managing Datasets

In [5]:
### if you have not installed pandas through the command line
### do so by opening a new command line tab/window, then 
### activate the virtual environment, and issue "pip install pandas"
### or, you may do "%pip install pandas" in a Jupyter notebook.
### do remember to comment out the installation line afterwards
### so that it would not run every time you run the cell

### we also need NumPy sometimes for processing data as it's the foundation of Pandas

# %pip install pandas
# %pip install numpy
import numpy as np
import pandas as pd

## Accessing Data Files

To access datasets (usually files), you can either: 
- set a path variable to the data folder, which will be easier in the long run; or
- write path (full or relative) and file names as arguments

You are learning these basic operations now and will probably just use **relative path** in the future.

### About path

When importing datasets, some path information are good to know: 
- Data paths: 
  - For macOS (and Linux), a full path starts with "`/`" (the "root") or you can use "`~`" to start with the user's home directory (e.g., "/Users/<user>`/`workspace/data/" == "`~`/workspace/data/"). 
  - In Windows, a full path includes a drive letter and backslashes for path separator (e.g. "`C:`\Users\<user>\workspace\dsm\data\") though forward slashes usually work as well.
- Current working directory (CWD)): You, from time to time, need to know your current working directory (or, where this Jupyter Notebook's location is), in order to access other files/directories from this CWD. To get your CWD, run `os.getcwd()`. 
- Home directory: To write portable code across OSs, we prefer `os.path.expanduser`, which can resolve the directory passed (in our case, usually `~`) for us to use. 
- `os.path.join`: This is used to join the path variable and the filename instead of hardcoding separators and literal paths, i.e., use `os.path.join( )` to join a path and a dataset file.
- Relative paths; Sometimes it's just easier to use relative path to access the data folders (e.g., `../../data/`).

As an example, the `os.getcwd()` function will give us the full path of the notebook you are working on.

In [6]:
import os               ### os is a standard library module that provides functions for interacting with the OS.
CWD = os.getcwd()
CWD                     ### print current working directory
                        ### this is where this Jupyter Notebook is located
### note this is the same as %pwd in a Jupyter Notebook
### this is the location of the Jupyter Notebook
### we will use this to access other files/folders
### relative to this location
### the result will vary different environments

'/Users/tcn85/workspace/dsm/chapters/05-pandas'

### Getting home directory

You can hardcode the path of your home directory (where you are when you start your terminal), but it is suggested to use `os.path.expanduser('~')` in Python environment, which works in different operating systems. 

For Windows users:

In [7]:
### if you are using macOS or Linux, you can use "~" to represent your home directory
### in Windows, you need to either use the full path (e.g., "C:/Users/[user]/...")
### or, you can use os.path.expanduser('~') to get your home directory in a cross-platform way

home = os.path.expanduser('~')

### when using Windows, getting the home path in the terminal would involve:
PS C:\Users\[user]> python
>>> import os
>>> os.path.expanduser('~')
'C:\\Users\\[user]'

SyntaxError: invalid syntax (4280512932.py, line 8)

In macOS or Linux:

In [ ]:
### we want to access the data directory so that we can read data files 
### without specifying the full path
### os.path.expanduser can be used to 

### you can expand ~ to the full user home path and keep the path as a string
### in the terminal/shell, it's $HOME but in Python it's os.path.expanduser('~')
home_dir = os.path.expanduser('~')

NameError: name 'os' is not defined


### Setting Path
- Setting the path is optional, but it comes in handy when you use the same data folder over time
- you can use a relative path or an absolute path to achieve this.

Following the steps:

1. import **os.path**

   `import os.path as path`

2. find and save **path**

    **Windows** users:
    ```powershell
    PS C:\Users\[user]\workspace\dsm> cd data
    PS C:\Users\[user]\workspace\dsm\data> pwd   ### pwd means present working directory
    Path
    ----
    C:\Users\[user]\workspace\dsm\data
    ```

   Then, in Jupyter Notebook:

    `data_path = 'C:\Users\[user]\workspace\dsm\data'`

   Or, use the home path: 

   `home = os.path.expanduser('~')
   data_path = os.path.join(home, 'workspace', 'dsm', 'data')`

   **macOS** users:

   ```bash
   (.venv) [uer]@[host]ː~/workspace/dsm$ cd data  
(.venv) [user]@[host]ː~/workspace/dsm/data$ pwd
    /Users/[user]/workspace/dsm/data

    ### the tilde (squiggly) means "user home directory"
    ```

    Then, in Jupyter Notebook:
    
    `data_path = '/Users/[user]/workspace/dsm/data'`    
    
    Or, use the home path:
       `home = os.path.expanduser('~')
    data_path = os.path.join(home, 'workspace', 'dsm', 'data')`


3. **path.join( )**

   `data = path.join(data_path, "data.csv")`   ### add the file with path.join( )

### Reading Dataset Files

Now let us read the dataset file using `pd.read_csv( )`. You may read the data file directly or and open it as a file and save it a variable so you can manipulate the data file.

In [11]:
### now we can read the data file using pandas
### this is one way to do it
home = os.path.expanduser('~')
data_path = os.path.join(home, 'workspace', 'dsm', 'data')
data = os.path.join(data_path, 'data.csv')
with open(data) as f:      ### open the file for reading and assign the file object variable f
    df = pd.read_csv(f)         ### read the csv file into a DataFrame
df.head()                       ### display the first 5 rows of the DataFrame

  Duration Pulse Maxpulse Calories
0       60   110      130    409.1
1       60   117      145      479
2       60   103      135      340
3       45   109      175    282.4
4       45   117      148      406

In [15]:
### just to show the path variables we used
data_path

'/Users/tcn85/workspace/dsm/data'

In summary, there are different ways of reading your datasets:

#### Use relative path

In [23]:
### another way to do it is to use relative path
### ../../data/data.csv
data = ("../../data/data.csv")
df = pd.read_csv(data)


##### read_csv directly

In [ ]:
df = pd.read_csv(data_path+"/data.csv")

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10

##### path.join

In [ ]:
data = os.path.join(data_path, "data.csv")
with open(data) as f:
    df = pd.read_csv(f)

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10

#### + to join path

In [21]:
with open(data_path+"/data.csv") as f:
    df = pd.read_csv(f)

##### change dir

In [ ]:
os.chdir(data_path)
df = pd.read_csv("data.csv")
df.describe()

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10