# Managing File Path

In [25]:
### if you have not installed pandas through the command line
### do so by opening a new command line tab/window, then 
### activate the virtual environment, and issue "pip install pandas"
### or, you may do "%pip install pandas" in a Jupyter notebook.
### do remember to comment out the installation line afterwards
### so that it would not run every time you run the cell

### we also need NumPy sometimes for processing data as it's the foundation of Pandas

# %pip install pandas
# %pip install numpy
import numpy as np
import pandas as pd

## Read Data Files

### About path

When importing datasets, some path information are good to know: 
- Data paths: 
  - For macOS (and Linux), a full path starts with "`/`" (the "root") or you can use "`~`" to start with the user's home directory (e.g., "/Users/<user>`/`workspace/data/" == "`~`/workspace/data/"). 
  - In Windows, a full path includes a drive letter and backslashes for path separator (e.g. "`C:`\Users\<user>\workspace\dsm\data\") though forward slashes usually work as well.
- `CWD` (current working directory): You, from time to time, need to know your current working directory (or, where this Jupyter Notebook's location is), in order to access other files/directories from this CWD. To get your CWD, do `CWD = os.getcwd()`. Then, when you need to access `workspace/dsm/data`, you need only to start with CWD. 
- `os.path.expanduser`: To write portable code across OSs, we prefer `os.path.expanduser`, which can solve the directory passed (in our case, usually `~`) 
- `os.path.join`: then we use `os.path.join` instead of hardcoding separators or literal paths to point to the path_folder and data file.
- Relative paths; Sometimes it's just easier to use relative path to access the data folders (`../../data/`).

In [5]:
import os               ### os is a standard library module that provides functions for interacting with the OS.
CWD = os.getcwd()
CWD                     ### print current working directory
                        ### this is where this Jupyter Notebook is located
### note this is the same as %pwd in a Jupyter Notebook
### this is the location of the Jupyter Notebook
### we will use this to access other files/folders
### relative to this location

'/Users/tychen/workspace/dsm/chapters/05-pandas'

### Get user home directory
- Use os.path.expanduser('~')

In [8]:
%script echo=False
### managing file path in Jupyter
PS C:\Users\[user]> python
>>> import os
>>> os.path.expanduser('~')
'C:\\Users\\tychen'
>>> home = os.path.expanduser('~')
>>> data_dir = os.path.join(home, 'workspace', 'dsm', 'data')
>>> data_file = os.path.join(data_dir, 'data.csv')
>>> data_file
'C:\\Users\\tychen\\workspace\\dsm\\data\\data.csv'
>>> exit()
%endscript

SyntaxError: invalid syntax (3118037240.py, line 3)

### Path to Dataset Files

Use `os.path.join( )` to join a path and a dataset file.

In [27]:
### we want to access the data directory so that we can read data files 
### without specifying the full path
### os.path.expanduser can be used to

### you can expand ~ to the full user home path and keep the path as a string
### in the terminal/shell, it's $HOME but in Python it's os.path.expanduser('~')
home_dir = os.path.expanduser('~')
data_dir = home_dir + '/workspace/dsm/data/'
if os.path.isdir(data_dir):		### check if the directory exists
	data_file = os.path.join(data_dir, 'data.csv')
 
data_file
### this is the full path to the data file data.csv 
### we can use this path to read the data file
### without worrying about the OS path separator

'/Users/tychen/workspace/dsm/data/data.csv'

Now let us read the dataset file using `pd.read_csv( )`. You may open the data file and save it a variable so you can manipulate the data file.

In [23]:
### now we can read the data file using pandas
### this is one way to do it
with open(data_file) as f:      ### open the file for reading and assign the file object variable f
    df = pd.read_csv(f)         ### read the csv file into a DataFrame
df.head()                       ### display the first 5 rows of the DataFrame

  Duration Pulse Maxpulse Calories
0       60   110      130    409.1
1       60   117      145      479
2       60   103      135      340
3       45   109      175    282.4
4       45   117      148      406

Otherwise, just read the file:

In [24]:
### another way to do it is to use relative path
### ../../data/data.csv
data = ("../../data/data.csv")
df = pd.read_csv(data)
df.head()

  Duration Pulse Maxpulse Calories
0       60   110      130    409.1
1       60   117      145      479
2       60   103      135      340
3       45   109      175    282.4
4       45   117      148      406

## Accessing Data Files

To access datasets (usually files), you can either: 
- set a path to the data folder, which will be easier in the long run; or
- write path and file names as arguments

You are learning these basic operations now and will probably just use **relative path** in the future.

### Setting Path
- Setting the path is optional, but it comes in handy when you use the same data folder over time
- you can use a relative path or an absolute path

Following the steps:

1. import **os.path**

   `import os.path as path`

2. find and save **path**

    **Windows** users:
    ```powershell
    PS C:\Users\[user]\workspace\dsm> cd data
    PS C:\Users\[user]\workspace\dsm\data> pwd   ### pwd means present working directory
    Path
    ----
    C:\Users\[user]\workspace\dsm\data
    ```

   Then, in Jupyter Notebook:

    `data_path = 'C:\Users\[user]\workspace\dsm\data'`


   **macOS** users:

   ```bash
   (.venv) [uer]@[host]ː~/workspace/dsm$ cd data  
(.venv) [user]@[host]ː~/workspace/dsm/data$ pwd
    /Users/[user]/workspace/dsm/data
    ```

    Then, in Jupyter Notebook:
    
    `data_path = '/Users/[user]/workspace/dsm/data'`      ### squiggly means "user home directory"

3. **path.join( )**

   `data = path.join(data_path, "data.csv")`   ### add the file with path.join( )

In [ ]:
data_path

'/Users/tcn85/workspace/dsm/data'

#### 3/3. Run df.describe()


##### 3/3.1  option 1: ##### works in macOS/Windows/Jupyter

In [ ]:
df = pd.read_csv(data_path+"/data.csv")
df.describe()

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10

####3/3.2 option 2: with open ##### works in macOS/Windows/Jupyter

In [ ]:
with open(data_path+"/data.csv") as f:
    df = pd.read_csv(f)
    df.describe()

##### option 3: path.join ##### works in mac/Windows/Jupyter

In [ ]:
data = path.join(data_path, "data.csv")
with open(data) as f:
    df = pd.read_csv(f)
df.describe()

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10

##### option 4: change dir ##### works in Windows 11/macOS

In [ ]:
os.chdir(data_path)
df = pd.read_csv("data.csv")
df.describe()

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10