# Pandas DataFrames

DataFrames are the workhorse of pandas and are directly inspired by the R programming language. We can think of a DataFrame as a bunch of Series objects put together to share the same index. Let's use pandas to explore this topic!

In [ ]:
import os.path as path
import pandas as pd
data_path = "../../../dsm/data"

print(data_path)

../../../dsm/data

#### Create DataFrame
1. path.join
2. with open as f:
3. pd.read_csv()

In [ ]:
data = path.join(data_path, "data.csv")

In [ ]:
with open(data) as f:
    df = pd.read_csv(f)

### Output
1. print(df): header(5) tail(5)
2. to_string() for whole df
3. pd.options.display.max_rows

In [ ]:
print(df)                             ##### 1. will give 5+5 == 10 rows by default

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

In [ ]:
print(pd.options.display.max_rows)     ##### 2. max_rows is 60 by default (depending on the system)

60

In [ ]:
pd.options.display.max_rows = 9999     ##### increase max_rows

In [ ]:
print(df)                              ##### showing many more rows

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145       479
2          60    103       135       340
3          45    109       175     282.4
4          45    117       148       406
5          60    102       127     300.5
6          60    110       136       374
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124       269
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123       275
15         60     98       120     215.2
16         60    100       120       300
17         45     90       112       NaN
18         60    103       123       323
19         45     97       125       243
20         60    108       131     364.2
21         45    100       119       282
22         60    130       101       300
23         45    105       132       246
24         60    102       126     334.5
25         60    100       120       250
26         60     92       118       241
27         60    103       132       NaN
28         60    100       132       280
29         60    102       129     380.3
30         60     92       115       243
31         45     90       112     180.1
32         60    101       124       299
33         60     93       113       223
34         60    107       136       361
35         60    114       140       415
36         60    102       127     300.5
37         60    100       120     300.1
38         60    100       120       300
39         45    104       129       266
40         45     90       112     180.1
41         60     98       126       286
42         60    100       122     329.4
43         60    111       138       400
44         60    111       131       397
45         60     99       119       273
46         60    109       153     387.6
47         45    111       136       300
48         45    108       129       298
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130       263
53         60    118       151       486
54         30    136       175       238
55         60    121       146     450.7
56         60    118       121       413
57         45    115       144       305
58         20    153       172     226.4
59         45    123       152       321
60        210    108       160      1376
61        160    110       137    1034.4
62        160    109       135       853
63         45    118       141       341
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130       816
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129      1115
71         60    109       153     387.6
72         90    100       127       700
73        150     97       127     953.2
74         45    114       146       304
75         90     98       125     563.2
76         45    105       134       251
77         45    110       141       300
78        120    100       130     500.4
79        270    100       131      1729
80         30    159       182     319.2
81         45    149       169       344
82         30    103       139     151.1
83        120    100       130       500
84         45    100       120     225.3
85         30    151       170     300.1
86         45    102       136       234
87        120    100       157    1000.1
88         45    129       103       242
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110       500
102        90     90       100       500
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128       124
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124       275
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141       443
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122       271
126        60     97       124     275.3
127        60    109       127       382
128        90     99       125     466.4
129        60    114       151       384
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133       335
133        60    106       132     327.5
134        60    103       136       339
135        20    136       156       189
136        45    117       143     317.7
137        45    115       137       318
138        45    113       138       308
139        20    141       162     222.4
140        60    108       135       390
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136       400
147        60    112       146     361.9
148        30    103       127       185
149        60    110       150     409.4
150        60    106       134       343
151        60    109       129     353.2
152        60    109       138       374
153        30    150       167     275.8
154        60    105       128       328
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130       270
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4
169  Duration  Pulse  Maxpulse  Calories
170        60    110       130     409.1
171        60    117       145       479
172        60    103       135       340
173        45    109       175     282.4
174        45    117       148       406
175        60    102       127     300.5
176        60    110       136       374
177        45    104       134     253.3
178        30    109       133     195.1
179        60     98       124       269
180        60    103       147     329.3
181        60    100       120     250.7
182        60    106       128     345.3
183        60    104       132     379.3
184        60     98       123       275
185        60     98       120     215.2
186        60    100       120       300
187        45     90       112       NaN
188        60    103       123       323
189        45     97       125       243
190        60    108       131     364.2
191        45    100       119       282
192        60    130       101       300
193        45    105       132       246
194        60    102       126     334.5
195        60    100       120       250
196        60     92       118       241
197        60    103       132       NaN
198        60    100       132       280
199        60    102       129     380.3
200        60     92       115       243
201        45     90       112     180.1
202        60    101       124       299
203        60     93       113       223
204        60    107       136       361
205        60    114       140       415
206        60    102       127     300.5
207        60    100       120     300.1
208        60    100       120       300
209        45    104       129       266
210        45     90       112     180.1
211        60     98       126       286
212        60    100       122     329.4
213        60    111       138       400
214        60    111       131       397
215        60     99       119       273
216        60    109       153     387.6
217        45    111       136       300
218        45    108       129       298
219        60    111       139     397.6
220        60    107       136     380.2
221        80    123       146     643.1
222        60    106       130       263
223        60    118       151       486
224        30    136       175       238
225        60    121       146     450.7
226        60    118       121       413
227        45    115       144       305
228        20    153       172     226.4
229        45    123       152       321
230       210    108       160      1376
231       160    110       137    1034.4
232       160    109       135       853
233        45    118       141       341
234        20    110       130     131.4
235       180     90       130     800.4
236       150    105       135     873.4
237       150    107       130       816
238        20    106       136     110.4
239       300    108       143    1500.2
240       150     97       129      1115
241        60    109       153     387.6
242        90    100       127       700
243       150     97       127     953.2
244        45    114       146       304
245        90     98       125     563.2
246        45    105       134       251
247        45    110       141       300
248       120    100       130     500.4
249       270    100       131      1729
250        30    159       182     319.2
251        45    149       169       344
252        30    103       139     151.1
253       120    100       130       500
254        45    100       120     225.3
255        30    151       170     300.1
256        45    102       136       234
257       120    100       157    1000.1
258        45    129       103       242
259        20     83       107      50.3
260       180    101       127     600.1
261        45    107       137       NaN
262        30     90       107     105.3
263        15     80       100      50.5
264        20    150       171     127.4
265        20    151       168     229.4
266        30     95       128     128.2
267        25    152       168     244.2
268        30    109       131     188.2
269        90     93       124     604.1
270        20     95       112      77.7
271        90     90       110       500
272        90     90       100       500
273        90     90       100     500.4
274        30     92       108      92.7
275        30     93       128       124
276       180     90       120     800.3
277        30     90       120      86.2
278        90     90       120     500.3
279       210    137       184    1860.4
280        60    102       124     325.2
281        45    107       124       275
282        15    124       139     124.2
283        45    100       120     225.3
284        60    108       131     367.6
285        60    108       151     351.7
286        60    116       141       443
287        60     97       122     277.4
288        60    105       125       NaN
289        60    103       124     332.7
290        30    112       137     193.9
291        45    100       120     100.7
292        60    119       169     336.7
293        60    107       127     344.9
294        60    111       151     368.5
295        60     98       122       271
296        60     97       124     275.3
297        60    109       127       382
298        90     99       125     466.4
299        60    114       151       384
300        60    104       134     342.5
301        60    107       138     357.5
302        60    103       133       335
303        60    106       132     327.5
304        60    103       136       339
305        20    136       156       189
306        45    117       143     317.7
307        45    115       137       318
308        45    113       138       308
309        20    141       162     222.4
310        60    108       135       390
311        60     97       127       NaN
312        45    100       120     250.4
313        45    122       149     335.4
314        60    136       170     470.2
315        45    106       126     270.8
316        60    107       136       400
317        60    112       146     361.9
318        30    103       127       185
319        60    110       150     409.4
320        60    106       134       343
321        60    109       129     353.2
322        60    109       138       374
323        30    150       167     275.8
324        60    105       128       328
325        60    111       151     368.5
326        60     97       131     270.4
327        60    100       120     270.4
328        60    114       150     382.8
329        30     80       120     240.9
330        30     85       120     250.4
331        45     90       130     260.4
332        45     95       130       270
333        45    100       140     280.9
334        60    105       140     290.8
335        60    110       145     300.4
336        60    115       145     310.2
337        75    120       150     320.4
338        75    125       150     330.4

In [ ]:
print(df.to_string())                  ##### 3. to_string() enabling print whole df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145       479
2          60    103       135       340
3          45    109       175     282.4
4          45    117       148       406
5          60    102       127     300.5
6          60    110       136       374
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124       269
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123       275
15         60     98       120     215.2
16         60    100       120       300
17         45     90       112       NaN
18         60    103       123       323
19         45     97       125       243
20         60    108       131     364.2
21         45    100       119       282
22         60    130       101       300
23         45    105       132       246
24         60    102       126     334.5
25         60    100       120       250
26         60     92       118       241
27         60    103       132       NaN
28         60    100       132       280
29         60    102       129     380.3
30         60     92       115       243
31         45     90       112     180.1
32         60    101       124       299
33         60     93       113       223
34         60    107       136       361
35         60    114       140       415
36         60    102       127     300.5
37         60    100       120     300.1
38         60    100       120       300
39         45    104       129       266
40         45     90       112     180.1
41         60     98       126       286
42         60    100       122     329.4
43         60    111       138       400
44         60    111       131       397
45         60     99       119       273
46         60    109       153     387.6
47         45    111       136       300
48         45    108       129       298
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130       263
53         60    118       151       486
54         30    136       175       238
55         60    121       146     450.7
56         60    118       121       413
57         45    115       144       305
58         20    153       172     226.4
59         45    123       152       321
60        210    108       160      1376
61        160    110       137    1034.4
62        160    109       135       853
63         45    118       141       341
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130       816
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129      1115
71         60    109       153     387.6
72         90    100       127       700
73        150     97       127     953.2
74         45    114       146       304
75         90     98       125     563.2
76         45    105       134       251
77         45    110       141       300
78        120    100       130     500.4
79        270    100       131      1729
80         30    159       182     319.2
81         45    149       169       344
82         30    103       139     151.1
83        120    100       130       500
84         45    100       120     225.3
85         30    151       170     300.1
86         45    102       136       234
87        120    100       157    1000.1
88         45    129       103       242
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110       500
102        90     90       100       500
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128       124
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124       275
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141       443
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122       271
126        60     97       124     275.3
127        60    109       127       382
128        90     99       125     466.4
129        60    114       151       384
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133       335
133        60    106       132     327.5
134        60    103       136       339
135        20    136       156       189
136        45    117       143     317.7
137        45    115       137       318
138        45    113       138       308
139        20    141       162     222.4
140        60    108       135       390
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136       400
147        60    112       146     361.9
148        30    103       127       185
149        60    110       150     409.4
150        60    106       134       343
151        60    109       129     353.2
152        60    109       138       374
153        30    150       167     275.8
154        60    105       128       328
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130       270
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4
169  Duration  Pulse  Maxpulse  Calories
170        60    110       130     409.1
171        60    117       145       479
172        60    103       135       340
173        45    109       175     282.4
174        45    117       148       406
175        60    102       127     300.5
176        60    110       136       374
177        45    104       134     253.3
178        30    109       133     195.1
179        60     98       124       269
180        60    103       147     329.3
181        60    100       120     250.7
182        60    106       128     345.3
183        60    104       132     379.3
184        60     98       123       275
185        60     98       120     215.2
186        60    100       120       300
187        45     90       112       NaN
188        60    103       123       323
189        45     97       125       243
190        60    108       131     364.2
191        45    100       119       282
192        60    130       101       300
193        45    105       132       246
194        60    102       126     334.5
195        60    100       120       250
196        60     92       118       241
197        60    103       132       NaN
198        60    100       132       280
199        60    102       129     380.3
200        60     92       115       243
201        45     90       112     180.1
202        60    101       124       299
203        60     93       113       223
204        60    107       136       361
205        60    114       140       415
206        60    102       127     300.5
207        60    100       120     300.1
208        60    100       120       300
209        45    104       129       266
210        45     90       112     180.1
211        60     98       126       286
212        60    100       122     329.4
213        60    111       138       400
214        60    111       131       397
215        60     99       119       273
216        60    109       153     387.6
217        45    111       136       300
218        45    108       129       298
219        60    111       139     397.6
220        60    107       136     380.2
221        80    123       146     643.1
222        60    106       130       263
223        60    118       151       486
224        30    136       175       238
225        60    121       146     450.7
226        60    118       121       413
227        45    115       144       305
228        20    153       172     226.4
229        45    123       152       321
230       210    108       160      1376
231       160    110       137    1034.4
232       160    109       135       853
233        45    118       141       341
234        20    110       130     131.4
235       180     90       130     800.4
236       150    105       135     873.4
237       150    107       130       816
238        20    106       136     110.4
239       300    108       143    1500.2
240       150     97       129      1115
241        60    109       153     387.6
242        90    100       127       700
243       150     97       127     953.2
244        45    114       146       304
245        90     98       125     563.2
246        45    105       134       251
247        45    110       141       300
248       120    100       130     500.4
249       270    100       131      1729
250        30    159       182     319.2
251        45    149       169       344
252        30    103       139     151.1
253       120    100       130       500
254        45    100       120     225.3
255        30    151       170     300.1
256        45    102       136       234
257       120    100       157    1000.1
258        45    129       103       242
259        20     83       107      50.3
260       180    101       127     600.1
261        45    107       137       NaN
262        30     90       107     105.3
263        15     80       100      50.5
264        20    150       171     127.4
265        20    151       168     229.4
266        30     95       128     128.2
267        25    152       168     244.2
268        30    109       131     188.2
269        90     93       124     604.1
270        20     95       112      77.7
271        90     90       110       500
272        90     90       100       500
273        90     90       100     500.4
274        30     92       108      92.7
275        30     93       128       124
276       180     90       120     800.3
277        30     90       120      86.2
278        90     90       120     500.3
279       210    137       184    1860.4
280        60    102       124     325.2
281        45    107       124       275
282        15    124       139     124.2
283        45    100       120     225.3
284        60    108       131     367.6
285        60    108       151     351.7
286        60    116       141       443
287        60     97       122     277.4
288        60    105       125       NaN
289        60    103       124     332.7
290        30    112       137     193.9
291        45    100       120     100.7
292        60    119       169     336.7
293        60    107       127     344.9
294        60    111       151     368.5
295        60     98       122       271
296        60     97       124     275.3
297        60    109       127       382
298        90     99       125     466.4
299        60    114       151       384
300        60    104       134     342.5
301        60    107       138     357.5
302        60    103       133       335
303        60    106       132     327.5
304        60    103       136       339
305        20    136       156       189
306        45    117       143     317.7
307        45    115       137       318
308        45    113       138       308
309        20    141       162     222.4
310        60    108       135       390
311        60     97       127       NaN
312        45    100       120     250.4
313        45    122       149     335.4
314        60    136       170     470.2
315        45    106       126     270.8
316        60    107       136       400
317        60    112       146     361.9
318        30    103       127       185
319        60    110       150     409.4
320        60    106       134       343
321        60    109       129     353.2
322        60    109       138       374
323        30    150       167     275.8
324        60    105       128       328
325        60    111       151     368.5
326        60     97       131     270.4
327        60    100       120     270.4
328        60    114       150     382.8
329        30     80       120     240.9
330        30     85       120     250.4
331        45     90       130     260.4
332        45     95       130       270
333        45    100       140     280.9
334        60    105       140     290.8
335        60    110       145     300.4
336        60    115       145     310.2
337        75    120       150     320.4
338        75    125       150     330.4

In [183]:
import pandas as pd
import numpy as np

In [184]:
from numpy.random import randn
np.random.seed(101)

In [185]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [186]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

#### Create DataFrame from np.random.randn

In [ ]:
### create the object. You see that the pd.date_range() function gives 
### a range of days just like a regular range() function

dates = pd.date_range("20250901", periods=6)

In [ ]:
### evaluate variable dates; dtype is datetime64 and freq='D'
dates

DatetimeIndex(['2025-09-01', '2025-09-02', '2025-09-03', '2025-09-04',
               '2025-09-05', '2025-09-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
### check data type of object
type(dates)

pandas.core.indexes.datetimes.DatetimeIndex

In [ ]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

In [ ]:
df

                   A         B         C         D
2025-09-01 -0.761298  1.939466  1.609120  1.036029
2025-09-02  1.195793 -0.705942 -1.869547  0.652774
2025-09-03 -0.415341  1.308874  0.370865 -0.887198
2025-09-04  0.891987 -0.832927  0.547284  0.026326
2025-09-05  0.936100 -0.731711 -0.960611  0.007647
2025-09-06  1.205913 -1.631140  0.737402  0.713350

## DataFrame Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [187]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [188]:
# Pass a list of column names
df[['W','Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [189]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

DataFrame Columns are just Series

In [190]:
type(df['W'])

pandas.core.series.Series

**Creating a new column:**

In [191]:
df['new'] = df['W'] + df['Y']

In [192]:
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

** Removing Columns**

In [193]:
df.drop('new',axis=1)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [194]:
# Not inplace unless specified!
df

          W         X         Y         Z       new
A  2.706850  0.628133  0.907969  0.503826  3.614819
B  0.651118 -0.319318 -0.848077  0.605965 -0.196959
C -2.018168  0.740122  0.528813 -0.589001 -1.489355
D  0.188695 -0.758872 -0.933237  0.955057 -0.744542
E  0.190794  1.978757  2.605967  0.683509  2.796762

In [195]:
df.drop('new',axis=1,inplace=True)

In [196]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

Can also drop rows this way:

In [197]:
df.drop('E',axis=0)

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

** Selecting Rows**

In [198]:
df.loc['A']

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

Or select based off of position instead of label

In [199]:
df.iloc[2]

W   -2.018168
X    0.740122
Y    0.528813
Z   -0.589001
Name: C, dtype: float64

** Selecting subset of rows and columns **

In [200]:
df.loc['B','Y']

-0.84807698340363147

In [201]:
df.loc[['A','B'],['W','Y']]

          W         Y
A  2.706850  0.907969
B  0.651118 -0.848077

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [202]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [203]:
df>0

       W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [204]:
df[df>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [205]:
df[df['W']>0]

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [206]:
df[df['W']>0]['Y']

A    0.907969
B   -0.848077
D   -0.933237
E    2.605967
Name: Y, dtype: float64

In [207]:
df[df['W']>0][['Y','X']]

          Y         X
A  0.907969  0.628133
B -0.848077 -0.319318
D -0.933237 -0.758872
E  2.605967  1.978757

For two conditions you can use | and & with parenthesis:

In [208]:
df[(df['W']>0) & (df['Y'] > 1)]

          W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [209]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [210]:
# Reset to default 0,1...n index
df.reset_index()

  index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [211]:
newind = 'CA NY WY OR CO'.split()

In [212]:
df['States'] = newind

In [213]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [214]:
df.set_index('States')

               W         X         Y         Z
States
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [215]:
df

          W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [216]:
df.set_index('States',inplace=True)

In [218]:
df

               W         X         Y         Z
States
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [253]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [254]:
hier_index

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           labels=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [257]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

             A         B
G1 1  0.153661  0.167638
   2 -0.765930  0.962299
   3  0.902826 -0.537909
G2 1 -1.549671  0.435253
   2  1.259904 -0.447898
   3  0.266207  0.412580

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [260]:
df.loc['G1']

          A         B
1  0.153661  0.167638
2 -0.765930  0.962299
3  0.902826 -0.537909

In [263]:
df.loc['G1'].loc[1]

A    0.153661
B    0.167638
Name: 1, dtype: float64

In [265]:
df.index.names

FrozenList([None, None])

In [266]:
df.index.names = ['Group','Num']

In [267]:
df

                  A         B
Group Num
G1    1    0.153661  0.167638
      2   -0.765930  0.962299
      3    0.902826 -0.537909
G2    1   -1.549671  0.435253
      2    1.259904 -0.447898
      3    0.266207  0.412580

In [270]:
df.xs('G1')

            A         B
Num
1    0.153661  0.167638
2   -0.765930  0.962299
3    0.902826 -0.537909

In [271]:
df.xs(['G1',1])

A    0.153661
B    0.167638
Name: (G1, 1), dtype: float64

In [273]:
df.xs(1,level='Num')

              A         B
Group
G1     0.153661  0.167638
G2    -1.549671  0.435253