# Pandas DataFrames

DataFrames are the core data structure in Pandas, modeled after similar structures in the **R** programming language. A DataFrame can be thought of as a **collection of Series objects** combined into a single table, all sharing the same index. Let’s use Pandas to explore how DataFrames work!

In this section, you will learn how to:

- create dataframes by accessing dataset **files**
- read data files
- output dataframes
- create dataframes from data **objects**

In [2]:
import numpy as np
import pandas as pd

## Accessing Dataset Files

To access datasets (usually files), you can either: 
- set a path to the data folder, which will be easier in the long run; or
- write path and file names as argument

### Setting Path
- Setting the path is optional, but it comes in handy when you use the same data folder over time
- you can use a relative path or an absolute path

Following the steps:

1. import **os.path**

   `import os.path as path`

2. find and save **path**

    **Windows** users:
    ```powershell
    PS C:\Users\[user]\workspace\dsm> cd data
    PS C:\Users\[user]\workspace\dsm\data> pwd   ### pwd means present working directory
    Path
    ----
    C:\Users\[user]\workspace\dsm\data
    ```


    Then, in Jupyter Notebook:

   
    `data_path = 'C:\Users\[user]\workspace\dsm\data'`


   **macOS** users:

   ```bash
   (.venv) [uer]@[host]ː~/workspace/dsm$ cd data  
(.venv) [user]@[host]ː~/workspace/dsm/data$ pwd
    /Users/[user]/workspace/dsm/data
    ```

    Then, in Jupyter Notebook:
    
    `data_path = '/Users/[user]/workspace/dsm/data'`      ### squiggly means "user home directory"

3. **path.join( )**

   `data = path.join(data_path, "data.csv")`   ### add the file with path.join( )

#### It works like this:
(3 steps)

In [6]:
### step 1
import os.path as path

### step 2
### Windows users use one of the following steps
# data_path = r"C:\Users\[user]\workspace\dsm\data"          ### r == raw strings
# data_path = "C:\\Users\\[user]\\workspace\\dsm\\data\\"    ### \ == escape sequence "\" double backslashes

### macOS users use this
data_path = '/Users/[user]/workspace/dsm/data'

### step 3
data = path.join(data_path, 'data.csv')

data

'/Users/[user]/workspace/dsm/data/data.csv'

### Path as Argument

You may choose to pass the path and file name information to **pd.read_csv( )** directly without setting a path. You can use either:
- full path, or
- relative path

#### Using absolute/full path

- Pointing to the file starting from the root of the directory structure.

In [8]:
### uncomment one of the following 

# df = pd.read_csv(r"C:\Users\tychen\workspace\dsm\data\data.csv")    ### Windows
df = pd.read_csv("/Users/tychen/workspace/thinkdsm/data/data.csv")       ### macOS
df

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

#### Using relative path

- Pointing to the file starting from the location of the working notebook

In [103]:
# df = pd.read_csv("..\\..\\data\\data.csv")    ### Windows
# df = pd.read_csv("../../data.csv")            ### macOS

In [104]:
df

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

## Reading Dataset Files

Once you have access to the (.csv) file, you can:

1. load the CSV file directly             
    ```python 
    df = pd.read_csv(data_file)          ### we usually use this method to read a file
    ```
    
2. open file: with **open( )**:
   ```python
   file = open(data_file, "r")           ### r == read; after done with the file, you need to close it
   df = pd.read_csv(file)
   ```
   
3. open file: using **with** statment:        
   ```python                               
   with open(data_file, "r") as file:    ### the with statement will close the file automatically 
       df = pd.read_csv(file)
    ```

In [109]:
### I encourage you to learn how to do this

with open(data) as f:                        ### you have the file variable f to use if you need to
    df = pd.read_csv(f)                      ### we usually just work with df

### read_csv( ) to read file
The most common way to read file.

In [107]:
### We set the data object earlier already

pd.read_csv(data)

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

## Output DataFrame

1. print(df): header(5) tail(5)
2. to_string() for whole df
3. pd.options.display.max_rows

In [9]:
df      ### default view is table-like
        ### Pandas will give 5+5 == 10 rows by default
        ### the shape information is at the bottom

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

In [10]:
print(df)   ### print(), same information but not as pretty

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

In [11]:
print(pd.options.display.max_rows)     ### 2. display max_rows is 60 by default (depending on the system)

60

In [12]:
pd.options.display.max_rows =  100     ### increase max_rows

In [13]:
print(df)                              ### showing many more rows ==> scrollable

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

In [53]:
# print(df.to_string())          ### 3. to_string() enabling print whole df

## Creating DataFrames

Creating a DataFrame in Pandas can be done in several ways:

  1. From a Python **Dictionary** (Most Common)
  2. From a **List** of Dictionaries
  3. From a List of Lists (with **Column** Names)
  4. From **Numpy Arrays**
  5. Create an Empty DataFrame

Check DataFrame Info

### Python dictionary to df

In [54]:
data = {
    "Name": ["Johnson", "Kylee", "Hector", "Cameryn"],        ### key : [ values ]
    "Age": [25, 30, 35, 24],                           ### key : [ values ]
    "City": ["Rolla", "St. Louis", "Chicago", "St. James"]      ### key : [ values ]
}

### Create DataFrame: key-value pair ==> Series (columns)

df = pd.DataFrame(data)
df

      Name  Age       City
0  Johnson   25      Rolla
1    Kylee   30  St. Louis
2   Hector   35    Chicago
3  Cameryn   24  St. James

### List of Dictionaries to df

In [55]:
### 4 dictionaries in the list

data = [
    {"Name": "Johnson", "Age": 25, "City": "Rolla"},
    {"Name": "Kylee", "Age": 30, "City": "St. Louis"},
    {"Name": "Hector", "Age": 35, "City": "Chicago"},
    {"Name": "Cameryn", "Age": 24, "City": "St. James"}
]

df = pd.DataFrame(data)
df

      Name  Age       City
0  Johnson   25      Rolla
1    Kylee   30  St. Louis
2   Hector   35    Chicago
3  Cameryn   24  St. James

### List of lists to df

In [56]:
data = [
    ["Johnson", 25, "Rolla"],
    ["Kylee", 30, "St. Louis"],
    ["Hector", 35, "Chicago"],
    ["Cameryn", 24, "St. James"]
]

columns = ["Name", "Age", "City"]

pd.DataFrame(data, columns = columns)

      Name  Age       City
0  Johnson   25      Rolla
1    Kylee   30  St. Louis
2   Hector   35    Chicago
3  Cameryn   24  St. James

### NumPy Arrays to df

If you are working with NumPy, you can pass an array directly.

In [59]:
data = np.array([
    ["Johnson", 25, "Rolla"],
    ["Kylee", 30, "St. Louis"],
    ["Hector", 35, "Chicago"],
    ["Cameryn", 24, "St. James"]
])

# pd.DataFrame(data)
pd.DataFrame(data, columns = ["Name", "Age", "City"])

      Name Age       City
0  Johnson  25      Rolla
1    Kylee  30  St. Louis
2   Hector  35    Chicago
3  Cameryn  24  St. James

### Create an Empty DataFrame

In [88]:
df_ppl = pd.DataFrame(columns=[ "Name", "Age", "City" ] )

### df is empty with column names

In [90]:
df_ppl.loc[0] = ["Johnson", 25, "Rolla"]
df_ppl.loc[1] = ["Kylee",   30, "St. Louis"]
df_ppl.loc[2] = ["Hector",  35, "Chicago"]
df_ppl.loc[3] = ["Cameryn", 24, "St. James"]

In [91]:
df_ppl

      Name  Age       City
0  Johnson   25      Rolla
1    Kylee   30  St. Louis
2   Hector   35    Chicago
3  Cameryn   24  St. James

### date_range( ) + randn to df

In [118]:
### create the object. You see that the pd.date_range() function gives 
### a range of days just like a regular range() function

dates = pd.date_range("20250901", periods=6)

In [119]:
### evaluate variable dates; dtype is datetime64 and freq='D'

dates

DatetimeIndex(['2025-09-01', '2025-09-02', '2025-09-03', '2025-09-04',
               '2025-09-05', '2025-09-06'],
              dtype='datetime64[ns]', freq='D')

In [120]:
### check data type of object

type(dates)

pandas.core.indexes.datetimes.DatetimeIndex

In [121]:
### use pd.DataFrame( ) to create a dataframe

np.random.seed(101)

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

In [122]:
df

                   A         B         C         D
2025-09-01  2.706850  0.628133  0.907969  0.503826
2025-09-02  0.651118 -0.319318 -0.848077  0.605965
2025-09-03 -2.018168  0.740122  0.528813 -0.589001
2025-09-04  0.188695 -0.758872 -0.933237  0.955057
2025-09-05  0.190794  1.978757  2.605967  0.683509
2025-09-06  0.302665  1.693723 -1.706086 -1.159119

## DataFrame from SQL Databases
Now, let us try to load the chinook SQLite database that we have used in the SQL database activity. You will be able to appreciate how convenient Pandas makes loading data to be:

1. load sqlite3 library (import; the sqlite module is part of the Python standard library)
2. connect to the database by calling the sqlite3.connect() function
3. use the Pandas function "read_sql_query()" to run your query
4. close the connection using the sqlite3 close() function

In [135]:
import sqlite3

conn = sqlite3.connect('../../data/chinook.db')           ### connection object
df = pd.read_sql_query("SELECT * FROM customer;", conn)   ### syntax: query + connection

df
print(df)

# conn.close()                                            ### close the connection after you are done

    CustomerId  FirstName      LastName  \
0            1       Luís     Gonçalves
1            2     Leonie        Köhler
2            3   François      Tremblay
3            4      Bjørn        Hansen
4            5  František   Wichterlová
5            6     Helena          Holý
6            7     Astrid        Gruber
7            8       Daan       Peeters
8            9       Kara       Nielsen
9           10    Eduardo       Martins
10          11  Alexandre         Rocha
11          12    Roberto       Almeida
12          13   Fernanda         Ramos
13          14       Mark       Philips
14          15   Jennifer      Peterson
15          16      Frank        Harris
16          17       Jack         Smith
17          18   Michelle        Brooks
18          19        Tim         Goyer
19          20        Dan        Miller
20          21      Kathy         Chase
21          22    Heather       Leacock
22          23       John        Gordon
23          24      Frank       Ralston
24          25     Victor       Stevens
25          26    Richard    Cunningham
26          27    Patrick          Gray
27          28      Julia       Barnett
28          29     Robert         Brown
29          30     Edward       Francis
30          31     Martha          Silk
31          32      Aaron      Mitchell
32          33      Ellie      Sullivan
33          34       João     Fernandes
34          35   Madalena       Sampaio
35          36     Hannah     Schneider
36          37       Fynn    Zimmermann
37          38     Niklas      Schröder
38          39    Camille       Bernard
39          40  Dominique      Lefebvre
40          41       Marc        Dubois
41          42      Wyatt        Girard
42          43   Isabelle       Mercier
43          44      Terhi    Hämäläinen
44          45   Ladislav        Kovács
45          46       Hugh      O'Reilly
46          47      Lucas       Mancini
47          48   Johannes  Van der Berg
48          49  Stanisław        Wójcik
49          50    Enrique         Muñoz
50          51     Joakim     Johansson
51          52       Emma         Jones
52          53       Phil        Hughes
53          54      Steve        Murray
54          55       Mark        Taylor
55          56      Diego     Gutiérrez
56          57       Luis         Rojas
57          58      Manoj        Pareek
58          59       Puja    Srivastava

                                             Company  \
0   Embraer - Empresa Brasileira de Aeronáutica S.A.
1                                               None
2                                               None
3                                               None
4                                   JetBrains s.r.o.
5                                               None
6                                               None
7                                               None
8                                               None
9                                   Woodstock Discos
10                              Banco do Brasil S.A.
11                                            Riotur
12                                              None
13                                             Telus
14                                     Rogers Canada
15                                       Google Inc.
16                             Microsoft Corporation
17                                              None
18                                        Apple Inc.
19                                              None
20                                              None
21                                              None
22                                              None
23                                              None
24                                              None
25                                              None
26                                              None
27                                              None
28                                              None
29                                              None
30                                              None
31                                              None
32                                              None
33                                              None
34                                              None
35                                              None
36                                              None
37                                              None
38                                              None
39                                              None
40                                              None
41                                              None
42                                              None
43                                              None
44                                              None
45                                              None
46                                              None
47                                              None
48                                              None
49                                              None
50                                              None
51                                              None
52                                              None
53                                              None
54                                              None
55                                              None
56                                              None
57                                              None
58                                              None

                                     Address                 City   State  \
0            Av. Brigadeiro Faria Lima, 2170  São José dos Campos      SP
1                    Theodor-Heuss-Straße 34            Stuttgart    None
2                          1498 rue Bélanger             Montréal      QC
3                           Ullevålsveien 14                 Oslo    None
4                              Klanova 9/506               Prague    None
5                              Rilská 3174/6               Prague    None
6       Rotenturmstraße 4, 1010 Innere Stadt               Vienne    None
7                            Grétrystraat 63             Brussels    None
8                        Sønder Boulevard 51           Copenhagen    None
9                  Rua Dr. Falcão Filho, 155            São Paulo      SP
10                        Av. Paulista, 2022            São Paulo      SP
11                          Praça Pio X, 119       Rio de Janeiro      RJ
12                              Qe 7 Bloco G             Brasília      DF
13                            8210 111 ST NW             Edmonton      AB
14                       700 W Pender Street            Vancouver      BC
15                 1600 Amphitheatre Parkway        Mountain View      CA
16                           1 Microsoft Way              Redmond      WA
17                              627 Broadway             New York      NY
18                           1 Infinite Loop            Cupertino      CA
19                      541 Del Medio Avenue        Mountain View      CA
20                          801 W 4th Street                 Reno      NV
21                          120 S Orange Ave              Orlando      FL
22                           69 Salem Street               Boston      MA
23                     162 E Superior Street              Chicago      IL
24                     319 N. Frances Street              Madison      WI
25                       2211 W Berry Street           Fort Worth      TX
26                           1033 N Park Ave               Tucson      AZ
27                               302 S 700 E       Salt Lake City      UT
28                    796 Dundas Street West              Toronto      ON
29                          230 Elgin Street               Ottawa      ON
30                     194A Chain Lake Drive              Halifax      NS
31                        696 Osborne Street             Winnipeg      MB
32                            5112 48 Street          Yellowknife      NT
33                        Rua da Assunção 53               Lisbon    None
34  Rua dos Campeões Europeus de Viena, 4350                Porto    None
35                        Tauentzienstraße 8               Berlin    None
36                          Berger Straße 10            Frankfurt    None
37                       Barbarossastraße 19               Berlin    None
38                             4, Rue Milton                Paris    None
39                            8, Rue Hanovre                Paris    None
40                       11, Place Bellecour                 Lyon    None
41                    9, Place Louis Barthou             Bordeaux    None
42                          68, Rue Jouvence                Dijon    None
43                           Porthaninkatu 9             Helsinki    None
44                         Erzsébet krt. 58.             Budapest    None
45                          3 Chatham Street               Dublin  Dublin
46                    Via Degli Scipioni, 43                 Rome      RM
47                     Lijnbaansgracht 120bg            Amsterdam      VV
48                              Ordynacka 10               Warsaw    None
49                        C/ San Bernardo 85               Madrid    None
50                               Celsiusg. 9            Stockholm    None
51                         202 Hoxton Street               London    None
52                              113 Lupus St               London    None
53                            110 Raeburn Pl           Edinburgh     None
54                         421 Bourke Street               Sidney     NSW
55                        307 Macacha Güemes         Buenos Aires    None
56                           Calle Lira, 198             Santiago    None
57                       12,Community Centre                Delhi    None
58                         3,Raj Bhavan Road            Bangalore    None

           Country  PostalCode                Phone                 Fax  \
0           Brazil   12227-000   +55 (12) 3923-5555  +55 (12) 3923-5566
1          Germany       70174     +49 0711 2842222                None
2           Canada     H2G 1A7    +1 (514) 721-4711                None
3           Norway        0171      +47 22 44 22 22                None
4   Czech Republic       14700     +420 2 4172 5555    +420 2 4172 5555
5   Czech Republic       14300     +420 2 4177 0449                None
6          Austria        1010       +43 01 5134505                None
7          Belgium        1000     +32 02 219 03 03                None
8          Denmark        1720       +453 3331 9991                None
9           Brazil   01007-010   +55 (11) 3033-5446  +55 (11) 3033-4564
10          Brazil   01310-200   +55 (11) 3055-3278  +55 (11) 3055-8131
11          Brazil   20040-020   +55 (21) 2271-7000  +55 (21) 2271-7070
12          Brazil   71020-677   +55 (61) 3363-5547  +55 (61) 3363-7855
13          Canada     T6G 2C7    +1 (780) 434-4554   +1 (780) 434-5565
14          Canada     V6C 1G8    +1 (604) 688-2255   +1 (604) 688-8756
15             USA  94043-1351    +1 (650) 253-0000   +1 (650) 253-0000
16             USA  98052-8300    +1 (425) 882-8080   +1 (425) 882-8081
17             USA  10012-2612    +1 (212) 221-3546   +1 (212) 221-4679
18             USA       95014    +1 (408) 996-1010   +1 (408) 996-1011
19             USA   94040-111    +1 (650) 644-3358                None
20             USA       89503    +1 (775) 223-7665                None
21             USA       32801    +1 (407) 999-7788                None
22             USA        2113    +1 (617) 522-1333                None
23             USA       60611    +1 (312) 332-3232                None
24             USA       53703    +1 (608) 257-0597                None
25             USA       76110    +1 (817) 924-7272                None
26             USA       85719    +1 (520) 622-4200                None
27             USA       84102    +1 (801) 531-7272                None
28          Canada     M6J 1V1    +1 (416) 363-8888                None
29          Canada     K2P 1L7    +1 (613) 234-3322                None
30          Canada     B3S 1C5    +1 (902) 450-0450                None
31          Canada     R3L 2B9    +1 (204) 452-6452                None
32          Canada     X1A 1N6    +1 (867) 920-2233                None
33        Portugal        None   +351 (213) 466-111                None
34        Portugal        None   +351 (225) 022-448                None
35         Germany       10789     +49 030 26550280                None
36         Germany       60316     +49 069 40598889                None
37         Germany       10779      +49 030 2141444                None
38          France       75009   +33 01 49 70 65 65                None
39          France       75002   +33 01 47 42 71 71                None
40          France       69002   +33 04 78 30 30 30                None
41          France       33000   +33 05 56 96 96 96                None
42          France       21000   +33 03 80 73 66 99                None
43         Finland       00530     +358 09 870 2000                None
44         Hungary      H-1073                 None                None
45         Ireland        None      +353 01 6792424                None
46           Italy       00192      +39 06 39733434                None
47     Netherlands        1016      +31 020 6223130                None
48          Poland      00-358     +48 22 828 37 39                None
49           Spain       28015      +34 914 454 454                None
50          Sweden       11230     +46 08-651 52 52                None
51  United Kingdom      N1 5LH    +44 020 7707 0707                None
52  United Kingdom    SW1V 3EN    +44 020 7976 5722                None
53  United Kingdom     EH4 1HH    +44 0131 315 3300                None
54       Australia        2010   +61 (02) 9332 3633                None
55       Argentina        1106  +54 (0)11 4311 4333                None
56           Chile        None    +56 (0)2 635 4444                None
57           India      110017    +91 0124 39883988                None
58           India      560001     +91 080 22289999                None

                            Email  SupportRepId
0            luisg@embraer.com.br             3
1           leonekohler@surfeu.de             5
2             ftremblay@gmail.com             3
3           bjorn.hansen@yahoo.no             4
4        frantisekw@jetbrains.com             4
5                 hholy@gmail.com             5
6          astrid.gruber@apple.at             5
7           daan_peeters@apple.be             4
8           kara.nielsen@jubii.dk             4
9        eduardo@woodstock.com.br             4
10               alero@uol.com.br             5
11  roberto.almeida@riotur.gov.br             3
12       fernadaramos4@uol.com.br             4
13             mphilips12@shaw.ca             5
14            jenniferp@rogers.ca             3
15             fharris@google.com             4
16        jacksmith@microsoft.com             5
17              michelleb@aol.com             3
18               tgoyer@apple.com             3
19            dmiller@comcast.com             4
20            kachase@hotmail.com             5
21             hleacock@gmail.com             4
22         johngordon22@yahoo.com             4
23             fralston@gmail.com             3
24             vstevens@yahoo.com             5
25       ricunningham@hotmail.com             4
26           patrick.gray@aol.com             4
27            jubarnett@gmail.com             5
28               robbrown@shaw.ca             3
29            edfrancis@yachoo.ca             3
30           marthasilk@gmail.com             5
31         aaronmitchell@yahoo.ca             4
32         ellie.sullivan@shaw.ca             3
33            jfernandes@yahoo.pt             4
34              masampaio@sapo.pt             4
35      hannah.schneider@yahoo.de             5
36           fzimmermann@yahoo.de             3
37            nschroder@surfeu.de             3
38       camille.bernard@yahoo.fr             4
39    dominiquelefebvre@gmail.com             4
40        marc.dubois@hotmail.com             5
41          wyatt.girard@yahoo.fr             3
42      isabelle_mercier@apple.fr             3
43      terhi.hamalainen@apple.fi             3
44       ladislav_kovacs@apple.hu             3
45           hughoreilly@apple.ie             3
46         lucas.mancini@yahoo.it             5
47        johavanderberg@yahoo.nl             5
48         stanisław.wójcik@wp.pl             4
49         enrique_munoz@yahoo.es             5
50      joakim.johansson@yahoo.se             5
51         emma_jones@hotmail.com             3
52          phil.hughes@gmail.com             3
53          steve.murray@yahoo.uk             5
54           mark.taylor@yahoo.au             4
55       diego.gutierrez@yahoo.ar             4
56             luisrojas@yahoo.cl             5
57        manoj.pareek@rediff.com             3
58       puja_srivastava@yahoo.in             3

In [138]:
### check data type: pd.read_sql_query() returns a df "DataFrame"

type(df)

pandas.core.frame.DataFrame

In [139]:
### type of conn is connection

type(conn)

sqlite3.Connection

## DataFrame Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

### randn & Index and Columns

Note that we have parameters to use in **pd.DataFrame( )**:

- index
- columns

In [140]:
from numpy.random import randn
np.random.seed(101)     ### this could be any number; fixate the "random" output

In [141]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [142]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [143]:
df['W']

A    2.706850
B    0.651118
C   -2.018168
D    0.188695
E    0.190794
Name: W, dtype: float64

In [144]:
# Pass a list of column names
df[['W','Z']]

          W         Z
A  2.706850  0.503826
B  0.651118  0.605965
C -2.018168 -0.589001
D  0.188695  0.955057
E  0.190794  0.683509

In [ ]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

DataFrame Columns are just Series

In [ ]:
type(df['W'])

**Creating a new column:**

In [ ]:
df['new'] = df['W'] + df['Y']

In [ ]:
df

** Removing Columns**

In [ ]:
df.drop('new',axis=1)

In [ ]:
# Not inplace unless specified!
df

In [ ]:
df.drop('new',axis=1,inplace=True)

In [ ]:
df

Can also drop rows this way:

In [ ]:
df.drop('E',axis=0)

** Selecting Rows**

In [ ]:
df.loc['A']

Or select based off of position instead of label

In [ ]:
df.iloc[2]

** Selecting subset of rows and columns **

In [ ]:
df.loc['B','Y']

In [ ]:
df.loc[['A','B'],['W','Y']]

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [ ]:
df

In [ ]:
df>0

In [ ]:
df[df>0]

In [ ]:
df[df['W']>0]

In [ ]:
df[df['W']>0]['Y']

In [ ]:
df[df['W']>0][['Y','X']]

For two conditions you can use | and & with parenthesis:

In [ ]:
df[(df['W']>0) & (df['Y'] > 1)]

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [ ]:
df

In [ ]:
# Reset to default 0,1...n index
df.reset_index()

In [ ]:
newind = 'CA NY WY OR CO'.split()

In [ ]:
df['States'] = newind

In [ ]:
df

In [ ]:
df.set_index('States')

In [ ]:
df

In [ ]:
df.set_index('States',inplace=True)

In [ ]:
df

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [ ]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [ ]:
hier_index

In [ ]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [ ]:
df.loc['G1']

In [ ]:
df.loc['G1'].loc[1]

In [ ]:
df.index.names

In [ ]:
df.index.names = ['Group','Num']

In [ ]:
df

In [ ]:
df.xs('G1')

In [ ]:
df.xs(['G1',1])

In [ ]:
df.xs(1,level='Num')