# Pandas DataFrames

DataFrames are the core data structure in Pandas, modeled after similar structures in the **R** programming language. A DataFrame can be thought of as a **collection of Series objects** combined into a single table, all sharing the same index. Let’s use Pandas to explore how DataFrames work!

In [87]:
import numpy as np
import pandas as pd

## Accessing Dataset Files

To access datasets (usually files), you can either: 
- set a path to the data folder, which will be easier in the long run; or
- write path and file names as argument

### Setting Path
- Setting the path is optional, but it comes in handy when you use the same data folder over time
- you can use a relative path or an absolute path

Following the steps:

1. import **os.path**

   `import os.path as path`

2. find and save **path**

    **Windows** users:
    ```powershell
    PS C:\Users\[user]\workspace\dsm> cd data
    PS C:\Users\[user]\workspace\dsm\data> pwd   ### pwd means present working directory
    Path
    ----
    C:\Users\[user]\workspace\dsm\data
    ```


    Then, in Jupyter Notebook:

   
    `data_path = 'C:\Users\[user]\workspace\dsm\data'`


   **macOS** users:

   ```bash
   (.venv) [uer]@[host]ː~/workspace/dsm$ cd data  
(.venv) [user]@[host]ː~/workspace/dsm/data$ pwd
    /Users/[user]/workspace/dsm/data
    ```

    Then, in Jupyter Notebook:
    
    `data_path = '/Users/[user]/workspace/dsm/data'`      ### squiggly means "user home directory"

3. **path.join( )**

   `data = path.join(data_path, "data.csv")`   ### add the file with path.join( )

#### It works like this:
(3 steps)

In [88]:
### step 1
import os.path as path

### step 2
### Windows users use one of the following steps
# data_path = r"C:\Users\[user]\workspace\dsm\data"          ### r == raw strings
# data_path = "C:\\Users\\[user]\\workspace\\dsm\\data\\"    ### \ == escape sequence "\" double backslashes

### macOS users use this
# data_path = '/Users/[user]/workspace/dsm/data'

### step 3
data = path.join(data_path, 'data.csv')

data

'/Users/tychen/workspace/thinkdsm/data\\data.csv'

### Path as Argument

You may choose to pass the path and file name information to **pd.read_csv( )** directly without setting a path. You can use either:
- full path, or
- relative path

#### Using absolute/full path

- Pointing to the file starting from the root of the directory structure.

In [108]:
# df = pd.read_csv(r"C:\Users\tychen\workspace\dsm\data\data.csv")    ### Windows
# df = pd.read_csv("/Users/[user]/workspace/dsm/data/data.csv")       ### macOS
df

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

#### Using relative path

- Pointing to the file starting from the location of the working notebook

In [103]:
# df = pd.read_csv("..\\..\\data\\data.csv")    ### Windows
# df = pd.read_csv("../../data.csv")            ### macOS

In [104]:
df

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

## Reading Datasets

Once you have access to the (.csv) file, you can:

1. load the CSV file directly             
    ```python 
    df = pd.read_csv(data_file)          ### we usually use this method to read a file
    ```
    
2. open file: with **open( )**:
   ```python
   file = open(data_file, "r")           ### r == read; after done with the file, you need to close it
   df = pd.read_csv(file)
   ```
   
3. open file: using **with** statment:        
   ```python                               
   with open(data_file, "r") as file:    ### the with statement will close the file automatically 
       df = pd.read_csv(file)
    ```

In [109]:
### I encourage you to learn how to do this

with open(data) as f:                        ### you have the file variable f to use if you need to
    df = pd.read_csv(f)                      ### we usually just work with df

### read_csv( ) to read file
The most common way to read file.

In [107]:
### We set the data object earlier already

pd.read_csv(data)

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

## df Output
1. print(df): header(5) tail(5)
2. to_string() for whole df
3. pd.options.display.max_rows

In [4]:
df      ### default view is table-like
        ### Pandas will give 5+5 == 10 rows by default
        ### the shape information is at the bottom

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

In [5]:
print(df)   ### print(), same information but not as pretty

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

In [6]:
print(pd.options.display.max_rows)     ### 2. display max_rows is 60 by default (depending on the system)

60

In [94]:
pd.options.display.max_rows =  100     ### increase max_rows

In [95]:
print(df)                              ### showing many more rows ==> scrollable

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

In [96]:
print(df.to_string())          ### 3. to_string() enabling print whole df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145       479
2          60    103       135       340
3          45    109       175     282.4
4          45    117       148       406
5          60    102       127     300.5
6          60    110       136       374
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124       269
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123       275
15         60     98       120     215.2
16         60    100       120       300
17         45     90       112       NaN
18         60    103       123       323
19         45     97       125       243
20         60    108       131     364.2
21         45    100       119       282
22         60    130       101       300
23         45    105       132       246
24         60    102       126     334.5
25         60    100       120       250
26         60     92       118       241
27         60    103       132       NaN
28         60    100       132       280
29         60    102       129     380.3
30         60     92       115       243
31         45     90       112     180.1
32         60    101       124       299
33         60     93       113       223
34         60    107       136       361
35         60    114       140       415
36         60    102       127     300.5
37         60    100       120     300.1
38         60    100       120       300
39         45    104       129       266
40         45     90       112     180.1
41         60     98       126       286
42         60    100       122     329.4
43         60    111       138       400
44         60    111       131       397
45         60     99       119       273
46         60    109       153     387.6
47         45    111       136       300
48         45    108       129       298
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130       263
53         60    118       151       486
54         30    136       175       238
55         60    121       146     450.7
56         60    118       121       413
57         45    115       144       305
58         20    153       172     226.4
59         45    123       152       321
60        210    108       160      1376
61        160    110       137    1034.4
62        160    109       135       853
63         45    118       141       341
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130       816
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129      1115
71         60    109       153     387.6
72         90    100       127       700
73        150     97       127     953.2
74         45    114       146       304
75         90     98       125     563.2
76         45    105       134       251
77         45    110       141       300
78        120    100       130     500.4
79        270    100       131      1729
80         30    159       182     319.2
81         45    149       169       344
82         30    103       139     151.1
83        120    100       130       500
84         45    100       120     225.3
85         30    151       170     300.1
86         45    102       136       234
87        120    100       157    1000.1
88         45    129       103       242
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110       500
102        90     90       100       500
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128       124
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124       275
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141       443
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122       271
126        60     97       124     275.3
127        60    109       127       382
128        90     99       125     466.4
129        60    114       151       384
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133       335
133        60    106       132     327.5
134        60    103       136       339
135        20    136       156       189
136        45    117       143     317.7
137        45    115       137       318
138        45    113       138       308
139        20    141       162     222.4
140        60    108       135       390
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136       400
147        60    112       146     361.9
148        30    103       127       185
149        60    110       150     409.4
150        60    106       134       343
151        60    109       129     353.2
152        60    109       138       374
153        30    150       167     275.8
154        60    105       128       328
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130       270
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.4
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4
169  Duration  Pulse  Maxpulse  Calories
170        60    110       130     409.1
171        60    117       145       479
172        60    103       135       340
173        45    109       175     282.4
174        45    117       148       406
175        60    102       127     300.5
176        60    110       136       374
177        45    104       134     253.3
178        30    109       133     195.1
179        60     98       124       269
180        60    103       147     329.3
181        60    100       120     250.7
182        60    106       128     345.3
183        60    104       132     379.3
184        60     98       123       275
185        60     98       120     215.2
186        60    100       120       300
187        45     90       112       NaN
188        60    103       123       323
189        45     97       125       243
190        60    108       131     364.2
191        45    100       119       282
192        60    130       101       300
193        45    105       132       246
194        60    102       126     334.5
195        60    100       120       250
196        60     92       118       241
197        60    103       132       NaN
198        60    100       132       280
199        60    102       129     380.3
200        60     92       115       243
201        45     90       112     180.1
202        60    101       124       299
203        60     93       113       223
204        60    107       136       361
205        60    114       140       415
206        60    102       127     300.5
207        60    100       120     300.1
208        60    100       120       300
209        45    104       129       266
210        45     90       112     180.1
211        60     98       126       286
212        60    100       122     329.4
213        60    111       138       400
214        60    111       131       397
215        60     99       119       273
216        60    109       153     387.6
217        45    111       136       300
218        45    108       129       298
219        60    111       139     397.6
220        60    107       136     380.2
221        80    123       146     643.1
222        60    106       130       263
223        60    118       151       486
224        30    136       175       238
225        60    121       146     450.7
226        60    118       121       413
227        45    115       144       305
228        20    153       172     226.4
229        45    123       152       321
230       210    108       160      1376
231       160    110       137    1034.4
232       160    109       135       853
233        45    118       141       341
234        20    110       130     131.4
235       180     90       130     800.4
236       150    105       135     873.4
237       150    107       130       816
238        20    106       136     110.4
239       300    108       143    1500.2
240       150     97       129      1115
241        60    109       153     387.6
242        90    100       127       700
243       150     97       127     953.2
244        45    114       146       304
245        90     98       125     563.2
246        45    105       134       251
247        45    110       141       300
248       120    100       130     500.4
249       270    100       131      1729
250        30    159       182     319.2
251        45    149       169       344
252        30    103       139     151.1
253       120    100       130       500
254        45    100       120     225.3
255        30    151       170     300.1
256        45    102       136       234
257       120    100       157    1000.1
258        45    129       103       242
259        20     83       107      50.3
260       180    101       127     600.1
261        45    107       137       NaN
262        30     90       107     105.3
263        15     80       100      50.5
264        20    150       171     127.4
265        20    151       168     229.4
266        30     95       128     128.2
267        25    152       168     244.2
268        30    109       131     188.2
269        90     93       124     604.1
270        20     95       112      77.7
271        90     90       110       500
272        90     90       100       500
273        90     90       100     500.4
274        30     92       108      92.7
275        30     93       128       124
276       180     90       120     800.3
277        30     90       120      86.2
278        90     90       120     500.3
279       210    137       184    1860.4
280        60    102       124     325.2
281        45    107       124       275
282        15    124       139     124.2
283        45    100       120     225.3
284        60    108       131     367.6
285        60    108       151     351.7
286        60    116       141       443
287        60     97       122     277.4
288        60    105       125       NaN
289        60    103       124     332.7
290        30    112       137     193.9
291        45    100       120     100.7
292        60    119       169     336.7
293        60    107       127     344.9
294        60    111       151     368.5
295        60     98       122       271
296        60     97       124     275.3
297        60    109       127       382
298        90     99       125     466.4
299        60    114       151       384
300        60    104       134     342.5
301        60    107       138     357.5
302        60    103       133       335
303        60    106       132     327.5
304        60    103       136       339
305        20    136       156       189
306        45    117       143     317.7
307        45    115       137       318
308        45    113       138       308
309        20    141       162     222.4
310        60    108       135       390
311        60     97       127       NaN
312        45    100       120     250.4
313        45    122       149     335.4
314        60    136       170     470.2
315        45    106       126     270.8
316        60    107       136       400
317        60    112       146     361.9
318        30    103       127       185
319        60    110       150     409.4
320        60    106       134       343
321        60    109       129     353.2
322        60    109       138       374
323        30    150       167     275.8
324        60    105       128       328
325        60    111       151     368.5
326        60     97       131     270.4
327        60    100       120     270.4
328        60    114       150     382.8
329        30     80       120     240.9
330        30     85       120     250.4
331        45     90       130     260.4
332        45     95       130       270
333        45    100       140     280.9
334        60    105       140     290.8
335        60    110       145     300.4
336        60    115       145     310.2
337        75    120       150     320.4
338        75    125       150     330.4

In [10]:
from numpy.random import randn
np.random.seed(101)

In [11]:
df = pd.DataFrame(randn(5,4),index='A B C D E'.split(),columns='W X Y Z'.split())

In [12]:
df

          W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

## Creating DataFrames

In [115]:
### create the object. You see that the pd.date_range() function gives 
### a range of days just like a regular range() function

dates = pd.date_range("20250901", periods=6)

In [120]:
### evaluate variable dates; dtype is datetime64 and freq='D'

dates

DatetimeIndex(['2025-09-01', '2025-09-02', '2025-09-03', '2025-09-04',
               '2025-09-05', '2025-09-06'],
              dtype='datetime64[ns]', freq='D')

In [121]:
### check data type of object

type(dates)

pandas.core.indexes.datetimes.DatetimeIndex

In [122]:
### use pd.DataFrame( ) to create a dataframe

df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))

In [17]:
df

                   A         B         C         D
2025-09-01  0.302665  1.693723 -1.706086 -1.159119
2025-09-02 -0.134841  0.390528  0.166905  0.184502
2025-09-03  0.807706  0.072960  0.638787  0.329646
2025-09-04 -0.497104 -0.754070 -0.943406  0.484752
2025-09-05 -0.116773  1.901755  0.238127  1.996652
2025-09-06 -0.993263  0.196800 -1.136645  0.000366

#### DataFrame from SQL Database
Now, let us try to load the chinook SQLite database that we have used in the SQL database activity. You will be able to appreciate how convenient Pandas makes loading data to be:

In [18]:
### to connect to a sqlite3 database, we:
### 1. load sqlite3 library (import; the sqlite module is part of the Python standard library)
### 2. connect to the database by calling the sqlite3.connect() function
### 3. use the Pandas function "read_sql_query()" to run your query
### 4. close the connection using the sqlite3 close() function

import sqlite3
conn = sqlite3.connect('../../data/chinook.db')
df = pd.read_sql_query("SELECT * FROM customer;", conn)
df

# print(df)
# conn.close()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,None,Theodor-Heuss-Straße 34,Stuttgart,None,Germany,70174,+49 0711 2842222,None,leonekohler@surfeu.de,5
2,3,François,Tremblay,None,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,None,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,None,Ullevålsveien 14,Oslo,None,Norway,0171,+47 22 44 22 22,None,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,None,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Holý,None,Rilská 3174/6,Prague,None,Czech Republic,14300,+420 2 4177 0449,None,hholy@gmail.com,5
6,7,Astrid,Gruber,None,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,None,Austria,1010,+43 01 5134505,None,astrid.gruber@apple.at,5
7,8,Daan,Peeters,None,Grétrystraat 63,Brussels,None,Belgium,1000,+32 02 219 03 03,None,daan_peeters@apple.be,4
8,9,Kara,Nielsen,None,Sønder Boulevard 51,Copenhagen,None,Denmark,1720,+453 3331 9991,None,kara.nielsen@jubii.dk,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
10,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
11,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
12,13,Fernanda,Ramos,None,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
13,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
14,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
15,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
16,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
17,18,Michelle,Brooks,None,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
18,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
19,20,Dan,Miller,None,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,None,dmiller@comcast.com,4
20,21,Kathy,Chase,None,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,None,kachase@hotmail.com,5
21,22,Heather,Leacock,None,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,None,hleacock@gmail.com,4
22,23,John,Gordon,None,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,None,johngordon22@yahoo.com,4
23,24,Frank,Ralston,None,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,None,fralston@gmail.com,3
24,25,Victor,Stevens,None,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,None,vstevens@yahoo.com,5
25,26,Richard,Cunningham,None,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,None,ricunningham@hotmail.com,4
26,27,Patrick,Gray,None,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,None,patrick.gray@aol.com,4
27,28,Julia,Barnett,None,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,None,jubarnett@gmail.com,5
28,29,Robert,Brown,None,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,None,robbrown@shaw.ca,3
29,30,Edward,Francis,None,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,None,edfrancis@yachoo.ca,3
30,31,Martha,Silk,None,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,None,marthasilk@gmail.com,5
31,32,Aaron,Mitchell,None,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,None,aaronmitchell@yahoo.ca,4
32,33,Ellie,Sullivan,None,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,None,ellie.sullivan@shaw.ca,3
33,34,João,Fernandes,None,Rua da Assunção 53,Lisbon,None,Portugal,None,+351 (213) 466-111,None,jfernandes@yahoo.pt,4
34,35,Madalena,Sampaio,None,"Rua dos Campeões Europeus de Viena, 4350",Porto,None,Portugal,None,+351 (225) 022-448,None,masampaio@sapo.pt,4
35,36,Hannah,Schneider,None,Tauentzienstraße 8,Berlin,None,Germany,10789,+49 030 26550280,None,hannah.schneider@yahoo.de,5
36,37,Fynn,Zimmermann,None,Berger Straße 10,Frankfurt,None,Germany,60316,+49 069 40598889,None,fzimmermann@yahoo.de,3
37,38,Niklas,Schröder,None,Barbarossastraße 19,Berlin,None,Germany,10779,+49 030 2141444,None,nschroder@surfeu.de,3
38,39,Camille,Bernard,None,"4, Rue Milton",Paris,None,France,75009,+33 01 49 70 65 65,None,camille.bernard@yahoo.fr,4
39,40,Dominique,Lefebvre,None,"8, Rue Hanovre",Paris,None,France,75002,+33 01 47 42 71 71,None,dominiquelefebvre@gmail.com,4
40,41,Marc,Dubois,None,"11, Place Bellecour",Lyon,None,France,69002,+33 04 78 30 30 30,None,marc.dubois@hotmail.com,5
41,42,Wyatt,Girard,None,"9, Place Louis Barthou",Bordeaux,None,France,33000,+33 05 56 96 96 96,None,wyatt.girard@yahoo.fr,3
42,43,Isabelle,Mercier,None,"68, Rue Jouvence",Dijon,None,France,21000,+33 03 80 73 66 99,None,isabelle_mercier@apple.fr,3
43,44,Terhi,Hämäläinen,None,Porthaninkatu 9,Helsinki,None,Finland,00530,+358 09 870 2000,None,terhi.hamalainen@apple.fi,3
44,45,Ladislav,Kovács,None,Erzsébet krt. 58.,Budapest,None,Hungary,H-1073,None,None,ladislav_kovacs@apple.hu,3
45,46,Hugh,O'Reilly,None,3 Chatham Street,Dublin,Dublin,Ireland,None,+353 01 6792424,None,hughoreilly@apple.ie,3
46,47,Lucas,Mancini,None,"Via Degli Scipioni, 43",Rome,RM,Italy,00192,+39 06 39733434,None,lucas.mancini@yahoo.it,5
47,48,Johannes,Van der Berg,None,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,None,johavanderberg@yahoo.nl,5
48,49,Stanisław,Wójcik,None,Ordynacka 10,Warsaw,None,Poland,00-358,+48 22 828 37 39,None,stanisław.wójcik@wp.pl,4
49,50,Enrique,Muñoz,None,C/ San Bernardo 85,Madrid,None,Spain,28015,+34 914 454 454,None,enrique_munoz@yahoo.es,5
50,51,Joakim,Johansson,None,Celsiusg. 9,Stockholm,None,Sweden,11230,+46 08-651 52 52,None,joakim.johansson@yahoo.se,5
51,52,Emma,Jones,None,202 Hoxton Street,London,None,United Kingdom,N1 5LH,+44 020 7707 0707,None,emma_jones@hotmail.com,3
52,53,Phil,Hughes,None,113 Lupus St,London,None,United Kingdom,SW1V 3EN,+44 020 7976 5722,None,phil.hughes@gmail.com,3
53,54,Steve,Murray,None,110 Raeburn Pl,Edinburgh,None,United Kingdom,EH4 1HH,+44 0131 315 3300,None,steve.murray@yahoo.uk,5
54,55,Mark,Taylor,None,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,None,mark.taylor@yahoo.au,4
55,56,Diego,Gutiérrez,None,307 Macacha Güemes,Buenos Aires,None,Argentina,1106,+54 (0)11 4311 4333,None,diego.gutierrez@yahoo.ar,4
56,57,Luis,Rojas,None,"Calle Lira, 198",Santiago,None,Chile,None,+56 (0)2 635 4444,None,luisrojas@yahoo.cl,5
57,58,Manoj,Pareek,None,"12,Community Centre",Delhi,None,India,110017,+91 0124 39883988,None,manoj.pareek@rediff.com,3
58,59,Puja,Srivastava,None,"3,Raj Bhavan Road",Bangalore,None,India,560001,+91 080 22289999,None,puja_srivastava@yahoo.in,3

In [19]:
### check data type: pd.read_sql_query() returns a df "DataFrame"
type(df)

pandas.core.frame.DataFrame

## DataFrame Selection and Indexing

Let's learn the various methods to grab data from a DataFrame

In [20]:
df['W']

KeyError: 'W'

In [ ]:
# Pass a list of column names
df[['W','Z']]

In [ ]:
# SQL Syntax (NOT RECOMMENDED!)
df.W

DataFrame Columns are just Series

In [ ]:
type(df['W'])

**Creating a new column:**

In [ ]:
df['new'] = df['W'] + df['Y']

In [ ]:
df

** Removing Columns**

In [ ]:
df.drop('new',axis=1)

In [ ]:
# Not inplace unless specified!
df

In [ ]:
df.drop('new',axis=1,inplace=True)

In [ ]:
df

Can also drop rows this way:

In [ ]:
df.drop('E',axis=0)

** Selecting Rows**

In [ ]:
df.loc['A']

Or select based off of position instead of label

In [ ]:
df.iloc[2]

** Selecting subset of rows and columns **

In [ ]:
df.loc['B','Y']

In [ ]:
df.loc[['A','B'],['W','Y']]

### Conditional Selection

An important feature of pandas is conditional selection using bracket notation, very similar to numpy:

In [ ]:
df

In [ ]:
df>0

In [ ]:
df[df>0]

In [ ]:
df[df['W']>0]

In [ ]:
df[df['W']>0]['Y']

In [ ]:
df[df['W']>0][['Y','X']]

For two conditions you can use | and & with parenthesis:

In [ ]:
df[(df['W']>0) & (df['Y'] > 1)]

## More Index Details

Let's discuss some more features of indexing, including resetting the index or setting it something else. We'll also talk about index hierarchy!

In [ ]:
df

In [ ]:
# Reset to default 0,1...n index
df.reset_index()

In [ ]:
newind = 'CA NY WY OR CO'.split()

In [ ]:
df['States'] = newind

In [ ]:
df

In [ ]:
df.set_index('States')

In [ ]:
df

In [ ]:
df.set_index('States',inplace=True)

In [ ]:
df

## Multi-Index and Index Hierarchy

Let us go over how to work with Multi-Index, first we'll create a quick example of what a Multi-Indexed DataFrame would look like:

In [ ]:
# Index Levels
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [ ]:
hier_index

In [ ]:
df = pd.DataFrame(np.random.randn(6,2),index=hier_index,columns=['A','B'])
df

Now let's show how to index this! For index hierarchy we use df.loc[], if this was on the columns axis, you would just use normal bracket notation df[]. Calling one level of the index returns the sub-dataframe:

In [ ]:
df.loc['G1']

In [ ]:
df.loc['G1'].loc[1]

In [ ]:
df.index.names

In [ ]:
df.index.names = ['Group','Num']

In [ ]:
df

In [ ]:
df.xs('G1')

In [ ]:
df.xs(['G1',1])

In [ ]:
df.xs(1,level='Num')