# Handling Datasets

After learning Python data structures (e.g., list, dictionary, tuple) and NumPy arrays, we are now ready to deal with data using Pandas. There are different file types used for datasets and we are going to learn how to import and export them in this section as part of data management using Pandas.

In [1]:
# if you have not installed pandas through the command line
# do so by opening a new command line tab/window, then
# activate the virtual environment, and issue "pip install pandas"
# or, you may do "%pip install pandas" in a Jupyter notebook.
# do remember to comment out the installation line afterwards
# so that it would not run every time you run the cell

# we also need NumPy sometimes for processing data as it's the foundation of Pandas

# %pip install pandas
# %pip install numpy
import numpy as np
import pandas as pd

## Accessing Dataset Files

To access datasets (usually files), you can either:

- set a path variable to the data folder, which will be easier in the long run; or
- write path (full or relative) and file names as arguments

You are learning these basic operations now and will probably just use **relative path** in the future.

When importing datasets, some path information are good to know:

1. **Full paths**:

   - **macOS** (and Linux): A full/absolute path starts with "`/`" (the "root" directory) or you can use "`~`" to start with the user's home directory (e.g., data_path = "/Users/<user>`/`workspace/data/" == "`~`/workspace/data/").

   - **Windows**: A full path includes a drive letter and backslashes (`\`) for path separator (e.g. data_path = "`C:`\Users\<user>\workspace\dsm\data\") though forward slashes usually work as well.

2. **Relative paths**: Usually it's just easier to use a relative path to access the data folders (e.g., `../../data/`).

3. Current working directory (CWD/PWD): To know your Current/Present Working Directory (this notebook's location), use `os.getcwd()` or `%pwd`.
   
4. Home directory: To write portable code across OSs, we prefer `os.path.expanduser`, which can resolve the directory passed (e.g., `~`) for us to use.

5. Join paths: This is used to join the path variable with the paths/filenames instead of hardcoding separators and literals. For example, `os.path.join( )` to join a path and a dataset file.

As an example, the `os.getcwd()` function will give us the full path of the notebook you are working on, which can be critical when using relative paths.

In [2]:
import os   ### os is a standard library module for interacting with the OS.
CWD = os.getcwd()
CWD  # print current working directory

'/Users/tychen/workspace/dsm/chapters/05-pandas'

### Getting home directory

You can hardcode the path of your home directory (where you are when you start your terminal), but it is suggested to use `os.path.expanduser('~')` in Python environment, which works in different operating systems.

For Windows users:

In [3]:
### if you are using macOS or Linux, you can use "~" to represent your home directory
### in Windows, you need to either use the full path (e.g., "C:/Users/[user]/...")
### or, you can use os.path.expanduser('~') to get your home directory in a cross-platform way
# we want to access the data directory so that we can read data files
# without specifying the full path
# os.path.expanduser can be used to
# you can expand ~ to the full user home path and keep the path as a string
# in the terminal/shell, it's $HOME but in Python it's os.path.expanduser('~')
home_dir = os.path.expanduser('~')

### Note that we'll use this variable later to construct the full path to the data directory:
data_path = os.path.join(home_dir, "workspace", "dsm", "data")

In macOS or Linux:

### Setting full path

- Setting paths is optional, but it comes in handy when you use the same data folder over time.
- you can use a relative path or a full/absolute path to achieve this.

Following the steps:

1.  import **os.path**:

    `import os.path as path`

2.  At the terminal, find and save the **full path**:

````{tab-set}

```{tab-item} **Windows**:
      PS C:\Users\[user]\workspace\dsm> cd data
      PS C:\Users\[user]\workspace\dsm\data> pwd   ### pwd: present working directory
      Path
      ----
      C:\Users\[user]\workspace\dsm\data

   Then, copy the path to your notebook:

      data_path = 'C:\Users\[user]\workspace\dsm\data'`
```

```{tab-item} **macOS**:

      (.venv) [uer]@[host]ː~/workspace/dsm$ cd data
      (.venv) [user]@[host]ː~/workspace/dsm/data$ pwd
      /Users/[user]/workspace/dsm/data

   Copy the full path to the notebook, then:

      data_path = '/Users/[user]/workspace/dsm/data'
```
````


3.  **Join path**:

    `data = path.join(data_path, "data.csv")` ### add the file with path.join( )

### Using relative path

To access a data set file in another folder (e.g., "data") in the project using a relative path, you know the relative location of the data need to provide a path in your code. For example: 

- if you are working on the `YOU-ARE-HERE.ipynb` notebook (see figure below), and you need to read the **example** file in the **data** directory, you need to say:

    `df = pd.read_csv('../data/example')`

- Other other hand, if you are working on the `YOU-MAY-BE-HERE.ipynb` notebook, and you need to read the **example** file in the **data** directory, you need to say:
    `df = pd.read_csv('../../data/example')`

Explanations: 
  - `..` means "go up one level in the directory tree structure." 
  - If you are working with  `YOU-MAY-BE-HERE.ipynb`, and you need to access the dataset file `example` in the `data` directory, you have to point Jupyter to go up **two** levels (the `folder` folder and the `notebooks` level) to the `dsm` folder, then at this level you can see the `data` folder to find `example`.

<div class="tab">
  <button class="tablinks" onclick="openTab(event, 'Windows')">Windows</button>
  <button class="tablinks" onclick="openTab(event, 'macOS')">macOS</button>
</div>

<div id="Windows" class="tabcontent">
  <pre><code>
(.venv) PS C:\Users\[user]\workspace\dsm> tree
Folder PATH listing
Volume serial number is 420C-3FF4
C:.
├───.ipynb_checkpoints
├───.venv
├── data
│   ├── actors.csv
│   ├── example
│   └── wine.csv
├── notebooks
│   ├── YOU-ARE-HERE.ipynb
│   └── folder
│       └── YOU-MAY-BE-HERE.ipynb
  </code></pre>
</div>

<div id="macOS" class="tabcontent" style="display:none">
  <pre><code>
  [user]@[host]ː~/workspace/dsm$ tree
.
├── data
│   ├── actors.csv
│   ├── example
│   └── wine.csv
├── notebooks
│   ├── YOU-ARE-HERE.ipynb
│   └── folder
│       └── YOU-MAY-BE-HERE.ipynb
  </code></pre>
</div>

<script>
function openTab(evt, tabName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(tabName).style.display = "block";
  evt.currentTarget.className += " active";
}
</script>

## Reading Dataset Files

Now let us read the dataset file using `pd.read_csv( )`. You may read the data file directly or and open it as a file and save it a variable so you can manipulate the data file.

In [4]:
# now we can read the data file using pandas
# this is one way to do it
home = os.path.expanduser('~')
data_path = os.path.join(home, 'workspace', 'dsm', 'data')
data = os.path.join(data_path, 'data.csv')
with open(data) as f:  # open the file for reading and assign the file object variable f
    df = pd.read_csv(f)  # read the csv file into a DataFrame
df.head()  # display the first 5 rows of the DataFrame

  Duration Pulse Maxpulse Calories
0       60   110      130    409.1
1       60   117      145      479
2       60   103      135      340
3       45   109      175    282.4
4       45   117      148      406

In [5]:
# just to show the path variables we used
data_path

'/Users/tychen/workspace/dsm/data'

In summary, there are different ways of reading your datasets:

#### Use relative path

In [6]:
# another way to do it is to use relative path
# ../../data/data.csv
data = ("../data/data.csv")
df = pd.read_csv(data)

FileNotFoundError: [Errno 2] No such file or directory: '../data/data.csv'

#### Path variable & filename

In [ ]:
df = pd.read_csv(data_path + "/data.csv")

#### Use `path.join`

In [ ]:
data = os.path.join(data_path, "data.csv")
df = pd.read_csv(data)

#### Use with statement
When you need to manipulate the file.

In [ ]:
with open(data_path+"/data.csv") as f:
    df = pd.read_csv(f)

#### change dir
Alternatively, change directory into the data folder and read the data from there.

In [ ]:
os.chdir(data_path)
df = pd.read_csv("data.csv")
df.describe()

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10

## Data Input and Output

This section serves as the reference code for obtaining input and output with Pandas. Pandas can read a variety of file types using its **pd.read_** methods. Here we cover the most common data types:

- CSV
- Excel
- HTML
- SQL

### CSV

#### CSV Input

In [ ]:
### note that you may need to change the path below to point to the correct location of the example file
df = pd.read_csv('../data/example')
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

#### CSV Output

In [ ]:
df.to_csv('example',index=False)
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### Excel
Pandas can read and write excel files, keep in mind, this only imports data. Not formulas or images, having images or macros may cause this read_excel method to crash.

#### Excel Input

- If you see the error message:

  <code>ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.</code>

  Install the dependency by issuing `%pip install openpyxl`

In [ ]:
### install dependencies if needed
# %pip install openpyxl

In [ ]:
### read Excel file
df = pd.read_excel('../data/Excel_Sample.xlsx', sheet_name='Sheet1')
df

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

In [ ]:
type(df)

pandas.core.frame.DataFrame

#### Excel Output

In [ ]:
### note this output will be in the same folder as your notebook

df.to_excel('Excel_Sample.xlsx', sheet_name='Sheet1')

### HTML

You may need to install htmllib5,lxml, and BeautifulSoup4. In your terminal/command prompt run:

    conda install lxml
    conda install html5lib
    conda install BeautifulSoup4

Then restart Jupyter Notebook.
(or use pip install if you aren't using the Anaconda Distribution)

Pandas can read table tabs off of html. For example:

#### HTML Input

- If you see the error message:

    `ImportError: Missing optional dependency 'lxml'.  Use pip or conda to install lxml.`

    Install the dependency: `%pip install lxml`

- **macOS users** do this to get rid of a certificate error ([4 steps](https://stackoverflow.com/questions/68275857/urllib-error-urlerror-urlopen-error-ssl-certificate-verify-failed-certifica) in the (.venv) lines: 
    ```bash
    (.venv) [user]@[host]ː~/workspace/dsm$ cd /Applications/Python 3.12/
(.venv) [user]@[host]ː/Applications/Python 3.12$ ls
        Icon?        Install Certificates.command Python Documentation.html        ReadMe.rtf
        IDLE.app     License.rtf      Python Launcher.app Update Shell Profile.command
    (.venv) [user]@[host]ː/Applications/Python 3.12$ ./Install\ Certificates.command 
    -- pip install --upgrade certifi
    Collecting certifi
      Using cached certifi-2025.8.3-py3-none-any.whl.metadata (2.4 kB)
    Using cached certifi-2025.8.3-py3-none-any.whl (161 kB)
    Installing collected packages: certifi
    Successfully installed certifi-2025.8.3
(.venv) [user]@[host]ː/Applications/Python 3.12$ cd ~/workspace/dsm
    ```

Pandas `read_html` function will read tables off of a webpage and return a list of DataFrame objects:

In [ ]:
##### install dependencies if needed
# %pip install lxml
# %pip install pandas

In [ ]:
import pandas as pd
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

In [ ]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
1,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
2,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
3,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
4,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
5,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
6,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
7,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
8,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
9,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
10,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
11,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
12,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
13,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
14,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
15,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
16,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
17,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
18,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
19,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
20,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
21,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
22,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
23,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524
24,Harvest Community Bank,Pennsville,New Jersey,34951,First-Citizens Bank & Trust Company,"January 13, 2017",10523

### SQL

([source](https://www.reddit.com/r/learnpython/comments/hgrekl/need_help_use_sql_on_a_dataframe_created_through/)) The pandas.io.sql module provides a collection of query wrappers to both facilitate data retrieval and to reduce dependency on DB-specific API. Database abstraction is provided by SQLAlchemy if installed. In addition you will need a driver library for your database. Examples of such drivers are psycopg2 for PostgreSQL or pymysql for MySQL. For SQLite this is included in Python’s standard library by default. You can find an overview of supported drivers for each SQL dialect in the SQLAlchemy docs.


If SQLAlchemy is not installed, a fallback is only provided for sqlite (and for mysql for backwards compatibility, but this is deprecated and will be removed in a future version). This mode requires a Python database adapter which respect the Python DB-API.

See also some cookbook examples for some advanced strategies.

The key functions are:

* read_sql_table(table_name, con[, schema, ...])	
    * Read SQL database table into a DataFrame.
* read_sql_query(sql, con[, index_col, ...])	
    * Read SQL query into a DataFrame.
* read_sql(sql, con[, index_col, ...])	
    * Read SQL query or database table into a DataFrame.
* DataFrame.to_sql(name, con[, flavor, ...])	
    * Write records stored in a DataFrame to a SQL database.

In [ ]:
# %pip install SQLAlchemy
from sqlalchemy import create_engine

In [ ]:
engine = create_engine('sqlite:///:memory:')

In [ ]:
print(type(df))
df = pd.DataFrame(df[0])

<class 'list'>

In [ ]:
df.to_sql('data', engine)

25

In [ ]:
sql_df = pd.read_sql('data',con=engine)

In [ ]:
sql_df

,index,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,0,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
1,1,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
2,2,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
3,3,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
4,4,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
5,5,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
6,6,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
7,7,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
8,8,Silicon Valley Bank,Santa Clara,California,24735,First Citizens Bank & Trust Company,"March 10, 2023",10539
9,9,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
10,10,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
11,11,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
12,12,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
13,13,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
14,14,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
15,15,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
16,16,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
17,17,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
18,18,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
19,19,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
20,20,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
21,21,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
22,22,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
23,23,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524
24,24,Harvest Community Bank,Pennsville,New Jersey,34951,First-Citizens Bank & Trust Company,"January 13, 2017",10523