## Managing File Path in Jupyter
#### 1/3. Import Libraries

In [304]:
import pandas as pd
import os
import os.path as path
# os.getcwd()
# os.chdir("data")
# os.chdir('')

#### 2/3. Create DataFrame
##### 1. assign data/datacsv to read_csv() 
##### 2. using with statement (file close automatically) 
##### 3. use path.join to join path and data
##### 4. use os.chdir then assign

In [3]:
data_path

'/Users/tcn85/workspace/dsm/data'

#### 3/3. Run df.describe()


##### 3/3.1  option 1: ##### works in macOS/Windows/Jupyter

In [4]:
df = pd.read_csv(data_path+"/data.csv")
df.describe()

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10

####3/3.2 option 2: with open ##### works in macOS/Windows/Jupyter

In [5]:
with open(data_path+"/data.csv") as f:
    df = pd.read_csv(f)
    df.describe()

##### option 3: path.join ##### works in mac/Windows/Jupyter

In [6]:
data = path.join(data_path, "data.csv")
with open(data) as f:
    df = pd.read_csv(f)
df.describe()

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10

##### option 4: change dir ##### works in Windows 11/macOS

In [7]:
os.chdir(data_path)
df = pd.read_csv("data.csv")
df.describe()

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10