# Data Input and Output

This section serves as the reference code for obtaining input and output with Pandas. Pandas can read a variety of file types using its **pd.read_** methods. Here we cover the most common data types:

- CSV
- Excel
- HTML
- SQL

In [7]:
import numpy as np
import pandas as pd

## Using relative path 

To access files in another folder in the project, you need to provide a path in your code. For example, if you are in the 02-YOU-ARE-HERE-**02**.ipynb, and you need to read the **example** file in the **data** directory, you need to say:

`df = pd.read_csv('../../data/example')`

- here, `..` means go up one level in the directory tree structure.

<div class="tab">
  <button class="tablinks" onclick="openTab(event, 'Windows')">Windows</button>
  <button class="tablinks" onclick="openTab(event, 'macOS')">macOS</button>
</div>

<div id="Windows" class="tabcontent">
  <pre><code>
(.venv) PS C:\Users\tychen\workspace\dsm> tree
Folder PATH listing
Volume serial number is 420C-3FF4
C:.
├───.ipynb_checkpoints
├───.venv
├── data
│   ├── actors.csv
│   ├── example
│   └── wine.csv
├── notebooks
│   ├── 02-np-YOU-ARE-HERE-01.ipynb
│   └── folder
│       └── 02-YOU-ARE-HERE-02.ipynb
  </code></pre>
</div>

<div id="macOS" class="tabcontent" style="display:none">
  <pre><code>
  [user]@[host]ː~/workspace/dsm$ tree
.
├── data
│   ├── actors.csv
│   ├── example
│   └── wine.csv
├── notebooks
│   ├── 02-np-YOU-ARE-HERE-01.ipynb
│   └── folder
│       └── 02-YOU-ARE-HERE-02.ipynb
  </code></pre>
</div>

<script>
function openTab(evt, tabName) {
  var i, tabcontent, tablinks;
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }
  document.getElementById(tabName).style.display = "block";
  evt.currentTarget.className += " active";
}
</script>

## CSV

### CSV Input

In [8]:
df = pd.read_csv('../../data/example')
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

### CSV Output

In [9]:
df.to_csv('example',index=False)

## Excel
Pandas can read and write excel files, keep in mind, this only imports data. Not formulas or images, having images or macros may cause this read_excel method to crash.

### Excel Input

- If you see the error message:

  <code>ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.</code>

  Install the dependency by issuing `%pip install openpyxl`

In [22]:
# %pip install openpyxl

In [23]:
pd.read_excel('../../data/Excel_Sample.xlsx', sheet_name='Sheet1')

   Unnamed: 0   a   b   c   d
0           0   0   1   2   3
1           1   4   5   6   7
2           2   8   9  10  11
3           3  12  13  14  15

### Excel Output

In [25]:
### note this output will be in the same folder as your notebook

df.to_excel('Excel_Sample.xlsx',sheet_name='Sheet1')

## HTML

You may need to install htmllib5,lxml, and BeautifulSoup4. In your terminal/command prompt run:

    conda install lxml
    conda install html5lib
    conda install BeautifulSoup4

Then restart Jupyter Notebook.
(or use pip install if you aren't using the Anaconda Distribution)

Pandas can read table tabs off of html. For example:

### HTML Input

- If you see the error message:

    `ImportError: Missing optional dependency 'lxml'.  Use pip or conda to install lxml.`

    Install the dependency: `%pip install lxml`

Pandas read_html function will read tables off of a webpage and return a list of DataFrame objects:

In [30]:
# %pip install lxml

In [38]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>

In [ ]:
df[0]


## SQL

The pandas.io.sql module provides a collection of query wrappers to both facilitate data retrieval and to reduce dependency on DB-specific API. Database abstraction is provided by SQLAlchemy if installed. In addition you will need a driver library for your database. Examples of such drivers are psycopg2 for PostgreSQL or pymysql for MySQL. For SQLite this is included in Python’s standard library by default. You can find an overview of supported drivers for each SQL dialect in the SQLAlchemy docs.


If SQLAlchemy is not installed, a fallback is only provided for sqlite (and for mysql for backwards compatibility, but this is deprecated and will be removed in a future version). This mode requires a Python database adapter which respect the Python DB-API.

See also some cookbook examples for some advanced strategies.

The key functions are:

* read_sql_table(table_name, con[, schema, ...])	
    * Read SQL database table into a DataFrame.
* read_sql_query(sql, con[, index_col, ...])	
    * Read SQL query into a DataFrame.
* read_sql(sql, con[, index_col, ...])	
    * Read SQL query or database table into a DataFrame.
* DataFrame.to_sql(name, con[, flavor, ...])	
    * Write records stored in a DataFrame to a SQL database.

In [ ]:
from sqlalchemy import create_engine

In [ ]:
engine = create_engine('sqlite:///:memory:')

In [ ]:
df.to_sql('data', engine)

In [ ]:
sql_df = pd.read_sql('data',con=engine)

In [ ]:
sql_df