# Cookbook
https://pandas.pydata.org/pandas-docs/stable/user_guide/cookbook.html#cookbook

In [22]:
import numpy as np
import pandas as pd

# %pip install -q blackcellmagic
# %load_ext blackcellmagic

# %pip install nb_black
# %load_ext nb_black
%pip install black
%load_ext black
%pip install autopep8

# %pip install jupyterlab-code-formatter black
# %black cookbook.ipynb

Requirement already satisfied: black in /Users/tychen/workspace/dsm/.venv/lib/python3.13/site-packages (21.12b0)
Requirement already satisfied: click>=7.1.2 in /Users/tychen/workspace/dsm/.venv/lib/python3.13/site-packages (from black) (8.3.0)
Requirement already satisfied: platformdirs>=2 in /Users/tychen/workspace/dsm/.venv/lib/python3.13/site-packages (from black) (4.4.0)
Requirement already satisfied: tomli<2.0.0,>=0.2.6 in /Users/tychen/workspace/dsm/.venv/lib/python3.13/site-packages (from black) (1.2.3)
Requirement already satisfied: pathspec<1,>=0.9.0 in /Users/tychen/workspace/dsm/.venv/lib/python3.13/site-packages (from black) (0.12.1)
Requirement already satisfied: typing-extensions>=3.10.0.0 in /Users/tychen/workspace/dsm/.venv/lib/python3.13/site-packages (from black) (4.15.0)
Requirement already satisfied: mypy-extensions>=0.4.3 in /Users/tychen/workspace/dsm/.venv/lib/python3.13/site-packages (from black) (1.1.0)
Note: you may need to restart the kernel to use updated packages.
The black module is not an IPython extension.
Requirement already satisfied: autopep8 in /Users/tychen/workspace/dsm/.venv/lib/python3.13/site-packages (2.3.2)
Requirement already satisfied: pycodestyle>=2.12.0 in /Users/tychen/workspace/dsm/.venv/lib/python3.13/site-packages (from autopep8) (2.14.0)
Note: you may need to restart the kernel to use updated packages.

## Idioms

In [52]:
np.arange(5, 10)
# list(range(5))

array([5, 6, 7, 8, 9])

In [59]:
df = pd.DataFrame(
    {
        "AAA": range(4, 8), 
        "BBB": np.arange(10, 50, 10), 
        "CCC": np.random.randint(10, 15, 4)
    }
)
df

   AAA  BBB  CCC
0    4   10   13
1    5   20   11
2    6   30   13
3    7   40   13

### if-then...

- An if-then on one column
- assignment changes the df

In [62]:
df.loc[df.AAA >= 5, "BBB"] = -1     ### 
df

   AAA  BBB  CCC
0    4   10   13
1    5   -1   11
2    6   -1   13
3    7   -1   13

if-then on 2 columns

In [65]:
df.loc[df.AAA >=5, ["BBB", "CCC"]] = 555
df

   AAA  BBB  CCC
0    4   10   13
1    5  555  555
2    6  555  555
3    7  555  555

Add another line with different logic, to do the -else

In [67]:
df.loc[df.AAA < 5, ["BBB", "CCC"]] = 2000
df

   AAA   BBB   CCC
0    4  2000  2000
1    5   555   555
2    6   555   555
3    7   555   555

Or use pandas where after you’ve set up a mask

In [75]:
df_mask = pd.DataFrame(
{
    "AAA": [True] * 4,
    "BBB": [False] * 4,
    "CCC": [True, False] * 2
}
)

df_mask

    AAA    BBB    CCC
0  True  False   True
1  True  False  False
2  True  False   True
3  True  False  False

In [79]:
### use the mask

df[ df_mask ]

   AAA  BBB     CCC
0    4  NaN  2000.0
1    5  NaN     NaN
2    6  NaN   555.0
3    7  NaN     NaN

In [80]:
### use where()

df.where(df_mask, -1000)

   AAA   BBB   CCC
0    4 -1000  2000
1    5 -1000 -1000
2    6 -1000   555
3    7 -1000 -1000

[if-then-else using NumPy’s where()](https://stackoverflow.com/questions/19913659/pandas-conditional-creation-of-a-series-dataframe-column)

In [245]:
df = pd.DataFrame(
    {
        "AAA": range(4, 8), 
        "BBB": np.arange(10, 50, 10), 
        # "CCC": np.random.randint(-50, 101, 10, 4)     ### randint does not support step
        "CCC": np.random.randint(-5, 11, 4)*10
    }
)

df

   AAA  BBB  CCC
0    4   10  100
1    5   20   60
2    6   30  -20
3    7   40   40

In [246]:
lst=[]
for i in range(1000000):
    # lst.append(np.random.randint(-5, 10.1, 4)*10)
    # lst.append((np.random.randint(-5, 10.1, 4)*10).tolist())
    # for ele in np.random.randint(-5, 10.1, 4)*10:
    for ele in np.random.randint(-5, 11, 4)*10:
        # lst.append(ele)
        lst.append(int(ele))

### import pprint
### pprint.pprint(lst, width=50, compact=True)
# print(lst)
# 100 in lst

In [249]:
df["logic"] = np.where(df["AAA"] > 5, "high", "low")
df

   AAA  BBB  CCC logic
0    4   10  100   low
1    5   20   60   low
2    6   30  -20  high
3    7   40   40  high

## Splitting

[Split a frame with a boolean criterion](https://stackoverflow.com/questions/14957116/how-to-split-a-dataframe-according-to-a-boolean-criterion)

In [251]:
df = pd.DataFrame(
    {
        "AAA": range(4, 8), 
        "BBB": np.arange(10, 50, 10), 
        # "CCC": np.random.randint(-50, 101, 10, 4)     ### randint does not support step
        "CCC": np.random.randint(-5, 11, 4)*10
    }
)

df

   AAA  BBB  CCC
0    4   10  100
1    5   20  -40
2    6   30   60
3    7   40   10

In [253]:
df["AAA"] <= 5

0     True
1     True
2    False
3    False
Name: AAA, dtype: bool

In [254]:
df[df.AAA <= 5]

   AAA  BBB  CCC
0    4   10  100
1    5   20  -40

In [255]:
df[df.AAA > 5]

   AAA  BBB  CCC
2    6   30   60
3    7   40   10