# Exercise. Pandas dtype: Questions [Extra Credit]

This exercise is for you to gain hands-on experience with managing data with Pandas and, to make it more interesting, handling a data type issue. This question is NOT EASY but realistic. 

In Pandas, there is pd.corr() function that generate a nice correlation table among the columns. While trying to use the function, you encounter an error. Upon close examination, you decide that this error is about...

- Create a blank Jupyter notebook in your dsm folder.
- Type up the code cells.
- The dataset (data-pd-corr.csv) is in Cavas Course Docs.
- Cell #8 is where you solve the problem.
- Type up your thoughts in cell #8.

In [1]:
### 1
import pandas as pd
import numpy as np
import os.path as path
data_path = "../../data/"
data = path.join(data_path, "data-pd-dtypes.csv")
# with open(data) as f:
#     df = pd.read_csv(f)
df = pd.read_csv(data)

In [6]:
## 2
### checking the object
df

    Duration Pulse Maxpulse Calories
0         60   110      130    409.1
1         60   117      145      479
2         60   103      135      340
3         45   109      175    282.4
4         45   117      148      406
..       ...   ...      ...      ...
334       60   105      140    290.8
335       60   110      145    300.4
336       60   115      145    310.2
337       75   120      150    320.4
338       75   125      150    330.4

[339 rows x 4 columns]

In [3]:
### 3
### checking the head

df.head()

  Duration Pulse Maxpulse Calories
0       60   110      130    409.1
1       60   117      145      479
2       60   103      135      340
3       45   109      175    282.4
4       45   117      148      406

In [4]:
### 4
### checking basic statistics

df.describe()

       Duration Pulse Maxpulse Calories
count       339   339      339      329
unique       17    48       58      146
top          60   100      120      300
freq        158    38       32       10

In [5]:
### 5

df.corr()
### does not work!

ValueError: could not convert string to float: 'Duration'

In [ ]:
### 6
### check the data types
df.dtypes
### float(df['Duration']).  ### does not work

In [ ]:
### 7
### convert Duration column to numeric, invalid parsing will become NaN
### IMPORTANT: errors='coerce' will replace non-convertible values with NaN
df['Duration'] = pd.to_numeric(df['Duration'], errors='coerce')
print(df.dtypes)

In [ ]:
### 8
df = pd.DataFrame({col: pd.to_numeric(df[col], errors='coerce') for col in df.columns})

In [ ]:
### 9
df.corr()